// Clacel 2.0 単語テスト問題（9月「1ヶ月分」、osh-vocab-test/data/*.pyから自動生成）
// answer は例文中の活用形を小文字で保持。判定時に両者を小文字化して比較する
// Day7/14/21/28は復習日のため欠番。Day9は12語、Day18は19語、Day29は19語（元データの語数通り）
module.exports = {
  label: "Clacel",
  series: [
    {
      name: "体験会",
      isTrial: true,
      items: [
        { sentence: "The dog likes to ___ holes in the garden.", answer: "dig", base: "dig", hint: "d__", ja: "掘る", sentenceJa: "その犬は庭に穴を掘るのが好きだ。" },
        { sentence: "She ___ her umbrella on the train yesterday.", answer: "left", base: "leave", hint: "l____", ja: "去る、残す、置き忘れる", sentenceJa: "彼女は昨日、電車に傘を置き忘れた。" },
        { sentence: "She likes to ___ pictures of animals.", answer: "draw", base: "draw", hint: "d___", ja: "描く、引く", sentenceJa: "彼女は動物の絵を描くのが好きだ。" },
        { sentence: "This textbook ___ all the basic grammar rules.", answer: "covers", base: "cover", hint: "c____", ja: "覆う、（話題を）扱う", sentenceJa: "この教科書は基本的な文法規則をすべて扱っている。" },
        { sentence: "Smith is a very ___ family name in England.", answer: "common", base: "common", hint: "c_____", ja: "一般的な、共通の", sentenceJa: "スミスはイギリスでとても一般的な姓だ。" },
        { sentence: "Sushi is made with ___ fish.", answer: "raw", base: "raw", hint: "r__", ja: "生の、未加工の", sentenceJa: "寿司は生の魚で作られる。" },
        { sentence: "The earth is a large ___ object.", answer: "round", base: "round", hint: "r____", ja: "丸い", sentenceJa: "地球は大きな丸い物体だ。" },
        { sentence: "Do we have ___ chairs for everyone?", answer: "enough", base: "enough", hint: "e_____", ja: "十分な", sentenceJa: "全員分の十分な椅子はあるだろうか？" },
        { sentence: "We need a ___ surface to set up the tent.", answer: "flat", base: "flat", hint: "f___", ja: "平らな", sentenceJa: "テントを張るには平らな地面が必要だ。" },
        { sentence: "Only a ___ students came to the early class.", answer: "few", base: "few", hint: "f__", ja: "ほとんどない、少しの", sentenceJa: "早朝の授業に来た学生はほとんどいなかった。" },
        { sentence: "Cut the bread into ___ slices.", answer: "thin", base: "thin", hint: "t___", ja: "薄い、細い", sentenceJa: "パンを薄く切ってください。" },
        { sentence: "My best friend lives ___ to my house.", answer: "close", base: "close", hint: "c____", ja: "近い、親しい", sentenceJa: "私の親友は私の家の近くに住んでいる。" },
        { sentence: "The bottle is completely ___.", answer: "empty", base: "empty", hint: "e____", ja: "空の", sentenceJa: "そのボトルは完全に空だ。" },
        { sentence: "Try to eat ___ and exercise more.", answer: "less", base: "less", hint: "l___", ja: "より少なく", sentenceJa: "食べる量を減らして、もっと運動するようにしてください。" },
        { sentence: "The movie was ___ good, actually.", answer: "pretty", base: "pretty", hint: "p_____", ja: "かなり、なかなか", sentenceJa: "その映画は実際、かなり良かった。" },
        { sentence: "He lives ___ in a small apartment.", answer: "alone", base: "alone", hint: "a____", ja: "一人で", sentenceJa: "彼は小さなアパートに一人で住んでいる。" },
        { sentence: "Have you finished your homework ___?", answer: "yet", base: "yet", hint: "y__", ja: "まだ、もう", sentenceJa: "もう宿題は終わった？" },
        { sentence: "Please ___ the door before you leave.", answer: "lock", base: "lock", hint: "l___", ja: "鍵をかける", sentenceJa: "出かける前にドアに鍵をかけてください。" },
        { sentence: "Last spring, they ___ trees along the road.", answer: "planted", base: "plant", hint: "p____", ja: "植える、仕込む", sentenceJa: "去年の春、彼らは道路沿いに木を植えた。" },
        { sentence: "He ___ more confident as the weeks passed.", answer: "grew", base: "grow", hint: "g___", ja: "育つ、〜になっていく", sentenceJa: "彼は数週間が経つにつれて自信を持つようになった。" },
      ],
    },
    {
      name: "Day 1",
      items: [
        { sentence: "Yesterday, the children ___ to be superheroes.", answer: "pretended", base: "pretend", hint: "p______", ja: "ふりをする", sentenceJa: "昨日、子供たちはスーパーヒーローのふりをした。" },
        { sentence: "Yesterday, she ___ her shoes before entering the room.", answer: "removed", base: "remove", hint: "r_____", ja: "取り除く", sentenceJa: "昨日、彼女は部屋に入る前に靴を脱いだ。" },
        { sentence: "She can't ___ the summer heat.", answer: "stand", base: "stand", hint: "s____", ja: "立つ、耐える", sentenceJa: "彼女は夏の暑さに耐えられない。" },
        { sentence: "The rising prices ___ many families.", answer: "concern", base: "concern", hint: "c______", ja: "心配させる、関係する", sentenceJa: "物価の上昇は多くの家庭を心配させている。" },
        { sentence: "Yesterday, he ___ an old classmate of his on the street.", answer: "recognized", base: "recognize", hint: "r________", ja: "認識する、見分ける、認める", sentenceJa: "昨日、彼は道で昔の同級生に気づいた。" },
        { sentence: "The dog likes to ___ holes in the garden.", answer: "dig", base: "dig", hint: "d__", ja: "掘る", sentenceJa: "その犬は庭に穴を掘るのが好きだ。" },
        { sentence: "News ___ quickly on social media.", answer: "spreads", base: "spread", hint: "s_____", ja: "広げる、広がる", sentenceJa: "ニュースはSNSで素早く広がる。" },
        { sentence: "Please don't ___ her while she is studying.", answer: "disturb", base: "disturb", hint: "d______", ja: "邪魔する", sentenceJa: "勉強している間は彼女の邪魔をしないでください。" },
        { sentence: "Yesterday, she ___ the difficult question very calmly.", answer: "handled", base: "handle", hint: "h_____", ja: "扱う、対処する、手を触れる", sentenceJa: "昨日、彼女はその難しい質問にとても冷静に対応した。" },
        { sentence: "Yesterday, he ___ an entire afternoon looking for his keys.", answer: "wasted", base: "waste", hint: "w____", ja: "無駄にする", sentenceJa: "昨日、彼は鍵を探すのに午後をまるまる無駄にした。" },
        { sentence: "I will ___ a meeting for next week.", answer: "arrange", base: "arrange", hint: "a______", ja: "手配する、整える", sentenceJa: "来週の会議を手配します。" },
        { sentence: "Many people ___ advice before making a big decision.", answer: "seek", base: "seek", hint: "s___", ja: "探し求める", sentenceJa: "多くの人は大きな決断をする前に助言を求める。" },
        { sentence: "The company ___ fresh vegetables to the school.", answer: "supplies", base: "supply", hint: "s_____", ja: "供給する", sentenceJa: "その会社は学校に新鮮な野菜を供給している。" },
        { sentence: "Yesterday, the teacher ___ the class into four groups.", answer: "divided", base: "divide", hint: "d_____", ja: "分ける、割る", sentenceJa: "昨日、先生はクラスを4つのグループに分けた。" },
        { sentence: "She ___ her umbrella on the train yesterday.", answer: "left", base: "leave", hint: "l____", ja: "去る、残す、置き忘れる", sentenceJa: "彼女は昨日、電車に傘を置き忘れた。" },
        { sentence: "He always ___ the same route to work.", answer: "follows", base: "follow", hint: "f_____", ja: "ついていく、従う", sentenceJa: "彼はいつも同じ道順で通勤している。" },
        { sentence: "She likes to ___ pictures of animals.", answer: "draw", base: "draw", hint: "d___", ja: "描く、引く", sentenceJa: "彼女は動物の絵を描くのが好きだ。" },
        { sentence: "This textbook ___ all the basic grammar rules.", answer: "covers", base: "cover", hint: "c____", ja: "覆う、（話題を）扱う", sentenceJa: "この教科書は基本的な文法規則をすべて扱っている。" },
        { sentence: "Childhood experiences often ___ our personalities.", answer: "shape", base: "shape", hint: "s____", ja: "形作る", sentenceJa: "幼少期の経験はしばしば私たちの性格を形作る。" },
        { sentence: "Last week, the store ___ open despite the storm.", answer: "remained", base: "remain", hint: "r_____", ja: "とどまる、～のままである、残る", sentenceJa: "先週、その店は嵐にもかかわらず営業を続けた。" },
      ],
    },
    {
      name: "Day 2",
      items: [
        { sentence: "Please ___ the plastic from the paper waste.", answer: "separate", base: "separate", hint: "s_______", ja: "分ける、分離する", sentenceJa: "プラスチックと紙ゴミを分けてください。" },
        { sentence: "Yesterday, she ___ to finish the report on time.", answer: "managed", base: "manage", hint: "m_____", ja: "なんとかやり遂げる、管理する", sentenceJa: "昨日、彼女は何とか時間通りにレポートを終わらせた。" },
        { sentence: "Last week, the storm ___ us to cancel the trip.", answer: "forced", base: "force", hint: "f____", ja: "強制する", sentenceJa: "先週、嵐のせいで私たちは旅行を中止せざるを得なかった。" },
        { sentence: "If you don't hurry, you'll ___ the bus.", answer: "miss", base: "miss", hint: "m___", ja: "逃す、寂しく思う", sentenceJa: "急がないとバスに乗り遅れますよ。" },
        { sentence: "This job ___ good communication skills.", answer: "requires", base: "require", hint: "r______", ja: "必要とする", sentenceJa: "この仕事は優れたコミュニケーション能力を必要としている。" },
        { sentence: "A ticket to the concert ___ fifty dollars.", answer: "costs", base: "cost", hint: "c___", ja: "（費用が）かかる、（労力・犠牲などを）要する", sentenceJa: "コンサートのチケットは50ドルする。" },
        { sentence: "This umbrella ___ to my sister.", answer: "belongs", base: "belong", hint: "b_____", ja: "所属する、〜のものである", sentenceJa: "この傘は私の妹のものだ。" },
        { sentence: "Can you ___ the man you saw?", answer: "describe", base: "describe", hint: "d_______", ja: "描写する、説明する", sentenceJa: "あなたが見た男性について説明してもらえますか？" },
        { sentence: "She ___ the piano for an hour every day.", answer: "practices", base: "practice", hint: "p_______", ja: "練習する", sentenceJa: "彼女は毎日1時間ピアノを練習している。" },
        { sentence: "Loud noises ___ me when I'm studying.", answer: "bother", base: "bother", hint: "b_____", ja: "悩ます、わざわざ〜する", sentenceJa: "勉強しているとき、大きな音は私を悩ませる。" },
        { sentence: "Please don't ___ answers from your classmate.", answer: "copy", base: "copy", hint: "c___", ja: "複写する、まねる", sentenceJa: "クラスメートの答えを写さないでください。" },
        { sentence: "Last night, he ___ on paying for dinner.", answer: "insisted", base: "insist", hint: "i_____", ja: "強く主張する", sentenceJa: "昨夜、彼は夕食代を払うと強く主張した。" },
        { sentence: "Be quiet as you ___ the sleeping baby.", answer: "approach", base: "approach", hint: "a_______", ja: "近づく", sentenceJa: "眠っている赤ちゃんに近づくときは静かにしてください。" },
        { sentence: "Please ___ me to call the dentist.", answer: "remind", base: "remind", hint: "r_____", ja: "思い出させる", sentenceJa: "歯医者に電話するのを私に思い出させてください。" },
        { sentence: "The two brothers often ___ about small things.", answer: "argue", base: "argue", hint: "a____", ja: "言い争う、主張する", sentenceJa: "その二人の兄弟はよく些細なことで言い争う。" },
        { sentence: "The band will ___ at the school festival.", answer: "perform", base: "perform", hint: "p______", ja: "行う、実行する、演じる", sentenceJa: "そのバンドは学園祭で演奏する予定だ。" },
        { sentence: "They had to ___ the game because of the rain.", answer: "cancel", base: "cancel", hint: "c_____", ja: "中止する", sentenceJa: "雨のため、彼らは試合を中止しなければならなかった。" },
        { sentence: "Washing your hands can ___ illness.", answer: "prevent", base: "prevent", hint: "p______", ja: "防ぐ", sentenceJa: "手を洗うことは病気を防ぐことができる。" },
        { sentence: "Could you help me ___ these boxes?", answer: "carry", base: "carry", hint: "c____", ja: "運ぶ", sentenceJa: "これらの箱を運ぶのを手伝ってもらえますか？" },
      ],
    },
    {
      name: "Day 3",
      items: [
        { sentence: "She hired a ___ to help with her math.", answer: "tutor", base: "tutor", hint: "t____", ja: "家庭教師、個別指導者", sentenceJa: "彼女は数学を手伝ってもらうために家庭教師を雇った。" },
        { sentence: "He made a good ___ at the interview.", answer: "impression", base: "impression", hint: "i_________", ja: "印象", sentenceJa: "彼は面接で良い印象を与えた。" },
        { sentence: "The ambassador lives in an official ___.", answer: "residence", base: "residence", hint: "r________", ja: "住居、邸宅", sentenceJa: "大使は公邸に住んでいる。" },
        { sentence: "I downloaded the latest ___ of the app.", answer: "version", base: "version", hint: "v______", ja: "版", sentenceJa: "私はそのアプリの最新版をダウンロードした。" },
        { sentence: "The ___ takes one year to circle the sun.", answer: "earth", base: "earth", hint: "e____", ja: "地球、大地", sentenceJa: "地球は太陽の周りを一周するのに一年かかる。" },
        { sentence: "Pollution has a serious ___ on the environment.", answer: "effect", base: "effect", hint: "e_____", ja: "影響、効果", sentenceJa: "汚染は環境に深刻な影響を与える。" },
        { sentence: "She passed the exam through hard ___.", answer: "effort", base: "effort", hint: "e_____", ja: "努力", sentenceJa: "彼女は努力の末、試験に合格した。" },
        { sentence: "The snacks are in the third ___ of the store.", answer: "aisle", base: "aisle", hint: "a____", ja: "通路", sentenceJa: "お菓子はその店の3番目の通路にある。" },
        { sentence: "Swimming is my favorite weekend ___.", answer: "activity", base: "activity", hint: "a_______", ja: "活動", sentenceJa: "水泳は私のお気に入りの週末の活動だ。" },
        { sentence: "The hero is the most popular ___ in the book.", answer: "character", base: "character", hint: "c________", ja: "性格、登場人物", sentenceJa: "その主人公はその本で最も人気のある登場人物だ。" },
        { sentence: "Children seem to have endless ___.", answer: "energy", base: "energy", hint: "e_____", ja: "エネルギー、活力", sentenceJa: "子どもたちは無限のエネルギーを持っているようだ。" },
        { sentence: "The ___ of the word is Latin.", answer: "origin", base: "origin", hint: "o_____", ja: "起源、由来", sentenceJa: "その単語の起源はラテン語だ。" },
        { sentence: "She raised an ___ to the new plan.", answer: "objection", base: "objection", hint: "o________", ja: "反対、異議", sentenceJa: "彼女は新しい計画に異議を唱えた。" },
        { sentence: "This is an effective ___ for learning words.", answer: "method", base: "method", hint: "m_____", ja: "方法", sentenceJa: "これは単語を覚えるのに効果的な方法だ。" },
        { sentence: "She kept her many ___ to herself during the meeting.", answer: "thoughts", base: "thought", hint: "t______", ja: "考え、思考", sentenceJa: "彼女は会議中、多くの考えを自分の中にとどめておいた。" },
        { sentence: "The old house was in a poor ___.", answer: "state", base: "state", hint: "s____", ja: "状態、（米国などの）州", sentenceJa: "その古い家はひどい状態だった。" },
        { sentence: "We enjoyed the beauty of ___ on our hike.", answer: "nature", base: "nature", hint: "n_____", ja: "自然、性質", sentenceJa: "私たちはハイキングで自然の美しさを楽しんだ。" },
        { sentence: "She sent her ___ for the scholarship.", answer: "application", base: "application", hint: "a__________", ja: "申し込み、応用、アプリ", sentenceJa: "彼女は奨学金のための申込書を送った。" },
        { sentence: "The painting has great ___ to collectors.", answer: "value", base: "value", hint: "v____", ja: "価値", sentenceJa: "その絵画はコレクターにとって大きな価値がある。" },
        { sentence: "The teacher explained the ___ calmly.", answer: "situation", base: "situation", hint: "s________", ja: "状況", sentenceJa: "先生はその状況を落ち着いて説明した。" },
      ],
    },
    {
      name: "Day 4",
      items: [
        { sentence: "Call this number in case of an ___.", answer: "emergency", base: "emergency", hint: "e________", ja: "緊急事態", sentenceJa: "緊急時はこの番号に電話してください。" },
        { sentence: "She deserves ___ for her hard work.", answer: "credit", base: "credit", hint: "c_____", ja: "信用、功績、クレジット", sentenceJa: "彼女は頑張った分の評価を受けるに値する。" },
        { sentence: "The ___ of the lake was perfectly calm.", answer: "surface", base: "surface", hint: "s______", ja: "表面", sentenceJa: "湖の水面は完全に穏やかだった。" },
        { sentence: "We asked the waiter for the ___.", answer: "bill", base: "bill", hint: "b___", ja: "請求書、勘定", sentenceJa: "私たちはウェイターに会計をお願いした。" },
        { sentence: "This is an important ___ we must discuss.", answer: "matter", base: "matter", hint: "m_____", ja: "事柄、問題", sentenceJa: "これは私たちが話し合わなければならない重要な問題だ。" },
        { sentence: "The clown's tricks were a source of ___.", answer: "amusement", base: "amusement", hint: "a________", ja: "楽しみ、娯楽", sentenceJa: "ピエロの芸は楽しみの種だった。" },
        { sentence: "The neighbors live together in ___.", answer: "harmony", base: "harmony", hint: "h______", ja: "調和", sentenceJa: "隣人たちは調和して暮らしている。" },
        { sentence: "The hotel room has a beautiful ___ of the sea.", answer: "view", base: "view", hint: "v___", ja: "眺め、見解", sentenceJa: "そのホテルの部屋からは海の美しい眺めが見える。" },
        { sentence: "The teacher praised the students' good ___.", answer: "behavior", base: "behavior", hint: "b_______", ja: "行動、ふるまい", sentenceJa: "先生は生徒たちの良い行動を褒めた。" },
        { sentence: "There was a long ___ before she answered.", answer: "pause", base: "pause", hint: "p____", ja: "休止、間", sentenceJa: "彼女が答える前に長い間があった。" },
        { sentence: "She learned a new ___ for painting.", answer: "technique", base: "technique", hint: "t________", ja: "技術、手法", sentenceJa: "彼女は絵を描く新しい技法を学んだ。" },
        { sentence: "There is a growing ___ toward healthy eating.", answer: "trend", base: "trend", hint: "t____", ja: "傾向、流行", sentenceJa: "健康的な食事を求める傾向が高まっている。" },
        { sentence: "The temperature dropped by ten ___ overnight.", answer: "degrees", base: "degree", hint: "d_____", ja: "度、学位、程度", sentenceJa: "気温は一晩で10度下がった。" },
        { sentence: "He was late because of a traffic ___.", answer: "accident", base: "accident", hint: "a_______", ja: "事故、偶然", sentenceJa: "彼は交通事故のせいで遅刻した。" },
        { sentence: "I do the ___ every Sunday morning.", answer: "laundry", base: "laundry", hint: "l______", ja: "洗濯（物）", sentenceJa: "私は毎週日曜日の朝に洗濯をする。" },
        { sentence: "She gave an excellent ___ in class.", answer: "presentation", base: "presentation", hint: "p___________", ja: "発表", sentenceJa: "彼女は授業で素晴らしい発表をした。" },
        { sentence: "He has a strong ___ of heights.", answer: "fear", base: "fear", hint: "f___", ja: "恐怖", sentenceJa: "彼は高所に対する強い恐怖心を持っている。" },
        { sentence: "This is a popular ___ for taking photos.", answer: "spot", base: "spot", hint: "s___", ja: "場所、斑点", sentenceJa: "ここは写真を撮るのに人気のある場所だ。" },
        { sentence: "Read all the ___ carefully before you start.", answer: "instructions", base: "instruction", hint: "i__________", ja: "指示、説明", sentenceJa: "始める前にすべての指示をよく読んでください。" },
        { sentence: "He ran for office as an ___.", answer: "independent", base: "independent", hint: "i__________", ja: "独立した人・もの", sentenceJa: "彼は無所属で立候補した。" },
      ],
    },
    {
      name: "Day 5",
      items: [
        { sentence: "We wore ___ clothes at the festival.", answer: "traditional", base: "traditional", hint: "t__________", ja: "伝統的な", sentenceJa: "私たちは祭りで伝統的な服を着た。" },
        { sentence: "The volunteer work gave her ___ experience.", answer: "valuable", base: "valuable", hint: "v_______", ja: "貴重な、価値のある", sentenceJa: "そのボランティア活動は彼女に貴重な経験を与えた。" },
        { sentence: "He wants to become a ___ soccer player.", answer: "professional", base: "professional", hint: "p___________", ja: "専門的な", sentenceJa: "彼はプロのサッカー選手になりたいと思っている。" },
        { sentence: "Can you tell me the ___ time of the meeting?", answer: "exact", base: "exact", hint: "e____", ja: "正確な", sentenceJa: "会議の正確な時間を教えてもらえますか？" },
        { sentence: "Smith is a very ___ family name in England.", answer: "common", base: "common", hint: "c_____", ja: "一般的な、共通の", sentenceJa: "スミスはイギリスでとても一般的な姓だ。" },
        { sentence: "Sushi is made with ___ fish.", answer: "raw", base: "raw", hint: "r__", ja: "生の、未加工の", sentenceJa: "寿司は生の魚で作られる。" },
        { sentence: "There is a ___ library near the station.", answer: "public", base: "public", hint: "p_____", ja: "公共の", sentenceJa: "駅の近くに公共図書館がある。" },
        { sentence: "Eating vegetables is part of a ___ diet.", answer: "healthy", base: "healthy", hint: "h______", ja: "健康的な、健康な", sentenceJa: "野菜を食べることは健康的な食事の一部だ。" },
        { sentence: "It is ___ to rain later this afternoon.", answer: "likely", base: "likely", hint: "l_____", ja: "ありそうな", sentenceJa: "今日の午後遅くに雨が降りそうだ。" },
        { sentence: "The two brothers have very ___ voices.", answer: "similar", base: "similar", hint: "s______", ja: "似ている", sentenceJa: "その兄弟は声がとてもよく似ている。" },
        { sentence: "Everyone should learn ___ first-aid skills.", answer: "basic", base: "basic", hint: "b____", ja: "基本的な", sentenceJa: "誰もが基本的な応急処置のスキルを学ぶべきだ。" },
        { sentence: "We had ___ chicken for dinner.", answer: "roast", base: "roast", hint: "r____", ja: "焼いた", sentenceJa: "夕食にローストチキンを食べた。" },
        { sentence: "The earth is a large ___ object.", answer: "round", base: "round", hint: "r____", ja: "丸い", sentenceJa: "地球は大きな丸い物体だ。" },
        { sentence: "Do we have ___ chairs for everyone?", answer: "enough", base: "enough", hint: "e_____", ja: "十分な", sentenceJa: "全員分の十分な椅子はあるだろうか？" },
        { sentence: "We had a ___ walk in the park.", answer: "pleasant", base: "pleasant", hint: "p_______", ja: "快い、感じのよい", sentenceJa: "私たちは公園で気持ちのよい散歩をした。" },
        { sentence: "Please give a ___ example in your answer.", answer: "specific", base: "specific", hint: "s_______", ja: "具体的な、特定の", sentenceJa: "答えには具体的な例を挙げてください。" },
        { sentence: "These shoes are light and ___.", answer: "comfortable", base: "comfortable", hint: "c__________", ja: "快適な", sentenceJa: "この靴は軽くて快適だ。" },
        { sentence: "She ate the ___ pizza by herself.", answer: "whole", base: "whole", hint: "w____", ja: "全体の", sentenceJa: "彼女はピザを一人で全部食べた。" },
        { sentence: "The baby is finally ___.", answer: "asleep", base: "asleep", hint: "a_____", ja: "眠って", sentenceJa: "赤ちゃんはついに眠った。" },
        { sentence: "He showed off his ___ smartphone.", answer: "brand-new", base: "brand-new", hint: "b________", ja: "新品の", sentenceJa: "彼は新品のスマートフォンを見せびらかした。" },
      ],
    },
    {
      name: "Day 6",
      items: [
        { sentence: "There is an ___ charge for late delivery.", answer: "additional", base: "additional", hint: "a_________", ja: "追加の", sentenceJa: "延着の場合は追加料金がかかります。" },
        { sentence: "We need a ___ surface to set up the tent.", answer: "flat", base: "flat", hint: "f___", ja: "平らな", sentenceJa: "テントを張るには平らな地面が必要だ。" },
        { sentence: "She is a ___ author in Japan.", answer: "well-known", base: "well-known", hint: "w_________", ja: "有名な", sentenceJa: "彼女は日本で有名な作家だ。" },
        { sentence: "A ___ storm hit the coast last night.", answer: "violent", base: "violent", hint: "v______", ja: "暴力的な、激しい", sentenceJa: "昨夜、激しい嵐が海岸を襲った。" },
        { sentence: "The train was very ___ this morning.", answer: "crowded", base: "crowded", hint: "c______", ja: "混雑した", sentenceJa: "今朝の電車はとても混雑していた。" },
        { sentence: "Only a ___ students came to the early class.", answer: "few", base: "few", hint: "f__", ja: "ほとんどない、少しの", sentenceJa: "早朝の授業に来た学生はほとんどいなかった。" },
        { sentence: "The old town has many ___ streets.", answer: "narrow", base: "narrow", hint: "n_____", ja: "狭い", sentenceJa: "旧市街には狭い通りがたくさんある。" },
        { sentence: "Cut the bread into ___ slices.", answer: "thin", base: "thin", hint: "t___", ja: "薄い、細い", sentenceJa: "パンを薄く切ってください。" },
        { sentence: "My best friend lives ___ to my house.", answer: "close", base: "close", hint: "c____", ja: "近い、親しい", sentenceJa: "私の親友は私の家の近くに住んでいる。" },
        { sentence: "I am ___ that I locked the door.", answer: "certain", base: "certain", hint: "c______", ja: "確信して、確かな", sentenceJa: "私はドアに鍵をかけたと確信している。" },
        { sentence: "Do you have this shirt in any ___ colors?", answer: "other", base: "other", hint: "o____", ja: "ほかの", sentenceJa: "このシャツはほかの色もありますか。" },
        { sentence: "Rain is ___ weather for this season.", answer: "typical", base: "typical", hint: "t______", ja: "典型的な", sentenceJa: "雨はこの季節の典型的な天気だ。" },
        { sentence: "She is ___ of the dark.", answer: "afraid", base: "afraid", hint: "a_____", ja: "恐れて、心配して", sentenceJa: "彼女は暗闇を恐れている。" },
        { sentence: "We will meet again the ___ week.", answer: "following", base: "following", hint: "f________", ja: "次の", sentenceJa: "私たちは次の週にまた会う予定だ。" },
        { sentence: "Is there a ___ train to the airport?", answer: "direct", base: "direct", hint: "d_____", ja: "直接の", sentenceJa: "空港まで直通の電車はありますか。" },
        { sentence: "This old book is ___ a lot of money.", answer: "worth", base: "worth", hint: "w____", ja: "～の価値がある", sentenceJa: "この古い本は大金の価値がある。" },
        { sentence: "The bottle is completely ___.", answer: "empty", base: "empty", hint: "e____", ja: "空の", sentenceJa: "そのボトルは完全に空だ。" },
        { sentence: "He ___ eats fast food.", answer: "rarely", base: "rarely", hint: "r_____", ja: "めったに～ない", sentenceJa: "彼はめったにファストフードを食べない。" },
        { sentence: "I have been to Kyoto only ___.", answer: "once", base: "once", hint: "o___", ja: "一度、かつて", sentenceJa: "私は一度しか京都に行ったことがない。" },
        { sentence: "The shop was ___ a small bakery.", answer: "originally", base: "originally", hint: "o_________", ja: "もともと、最初は", sentenceJa: "その店はもともと小さなパン屋だった。" },
      ],
    },
    {
      name: "Day 8",
      items: [
        { sentence: "The train left at ___ nine o'clock.", answer: "exactly", base: "exactly", hint: "e______", ja: "正確に、ちょうど", sentenceJa: "電車はちょうど9時に出発した。" },
        { sentence: "Try to eat ___ and exercise more.", answer: "less", base: "less", hint: "l___", ja: "より少なく", sentenceJa: "食べる量を減らして、もっと運動するようにしてください。" },
        { sentence: "___, the weather will be sunny tomorrow.", answer: "hopefully", base: "hopefully", hint: "h________", ja: "願わくは、うまくいけば", sentenceJa: "願わくは、明日は晴れますように。" },
        { sentence: "The customers are ___ young students.", answer: "mostly", base: "mostly", hint: "m_____", ja: "たいてい、主に", sentenceJa: "お客さんはたいてい若い学生です。" },
        { sentence: "I ___ forgot about the meeting.", answer: "completely", base: "completely", hint: "c_________", ja: "完全に", sentenceJa: "私はその会議のことを完全に忘れていた。" },
        { sentence: "The flowers were arranged very ___.", answer: "nicely", base: "nicely", hint: "n_____", ja: "うまく、よく", sentenceJa: "花はとても上手に生けられていた。" },
        { sentence: "The test was ___ difficult this time.", answer: "rather", base: "rather", hint: "r_____", ja: "かなり、むしろ", sentenceJa: "今回のテストはかなり難しかった。" },
        { sentence: "The movie was ___ good, actually.", answer: "pretty", base: "pretty", hint: "p_____", ja: "かなり、なかなか", sentenceJa: "その映画は実際、かなり良かった。" },
        { sentence: "She wants to study ___ next year.", answer: "abroad", base: "abroad", hint: "a_____", ja: "海外で、海外へ", sentenceJa: "彼女は来年、海外に留学したいと思っている。" },
        { sentence: "He lives ___ in a small apartment.", answer: "alone", base: "alone", hint: "a____", ja: "一人で", sentenceJa: "彼は小さなアパートに一人で住んでいる。" },
        { sentence: "Have you finished your homework ___?", answer: "yet", base: "yet", hint: "y__", ja: "まだ、もう", sentenceJa: "もう宿題は終わった？" },
        { sentence: "She solved the puzzle ___.", answer: "easily", base: "easily", hint: "e_____", ja: "簡単に", sentenceJa: "彼女はそのパズルを簡単に解いた。" },
        { sentence: "I don't play that game ___.", answer: "anymore", base: "anymore", hint: "a______", ja: "もはや〜ない", sentenceJa: "私はもうそのゲームをしない。" },
        { sentence: "You can call me ___ you need help.", answer: "anytime", base: "anytime", hint: "a______", ja: "いつでも", sentenceJa: "助けが必要なときはいつでも電話していいよ。" },
        { sentence: "It's cold today. It was warm yesterday, ___.", answer: "though", base: "though", hint: "t_____", ja: "でも、もっとも", sentenceJa: "今日は寒い。でも昨日は暖かかった。" },
        { sentence: "It was raining ___ all morning.", answer: "heavily", base: "heavily", hint: "h______", ja: "激しく、大量に", sentenceJa: "午前中ずっと激しく雨が降っていた。" },
        { sentence: "I'm ___ finished with my report.", answer: "almost", base: "almost", hint: "a_____", ja: "ほとんど", sentenceJa: "レポートはほとんど終わっている。" },
        { sentence: "After many tries, he ___ succeeded.", answer: "eventually", base: "eventually", hint: "e_________", ja: "結局、ついに", sentenceJa: "何度も挑戦した後、彼はついに成功した。" },
        { sentence: "I could ___ hear her quiet voice.", answer: "hardly", base: "hardly", hint: "h_____", ja: "ほとんど〜ない", sentenceJa: "彼女の小さな声はほとんど聞こえなかった。" },
        { sentence: "The exam was ___ easy for most students.", answer: "quite", base: "quite", hint: "q____", ja: "かなり、まったく", sentenceJa: "試験はほとんどの生徒にとってかなり簡単だった。" },
      ],
    },
    {
      name: "Day 9",
      items: [
        { sentence: "Please call me ___ if there is a problem.", answer: "immediately", base: "immediately", hint: "i__________", ja: "すぐに", sentenceJa: "問題があれば、すぐに私に電話してください。" },
        { sentence: "We had dinner and went for a walk ___.", answer: "afterward", base: "afterward", hint: "a________", ja: "あとで", sentenceJa: "私たちは夕食をとり、その後散歩に行った。" },
        { sentence: "The café was closed, so we went to the park ___.", answer: "instead", base: "instead", hint: "i______", ja: "代わりに", sentenceJa: "そのカフェは閉まっていたので、代わりに公園へ行った。" },
        { sentence: "We'll go hiking ___ it rains.", answer: "unless", base: "unless", hint: "u_____", ja: "～でない限り", sentenceJa: "雨が降らない限り、ハイキングに行くつもりだ。" },
        { sentence: "___ it was raining, we enjoyed the trip.", answer: "although", base: "although", hint: "a_______", ja: "～だけれども", sentenceJa: "雨が降っていたけれども、私たちは旅行を楽しんだ。" },
        { sentence: "The shop is open every day ___ Sunday.", answer: "except", base: "except", hint: "e_____", ja: "～を除いて", sentenceJa: "その店は日曜日を除いて毎日営業している。" },
        { sentence: "The cat is hiding ___ the sofa.", answer: "behind", base: "behind", hint: "b_____", ja: "～の後ろに", sentenceJa: "猫はソファの後ろに隠れている。" },
        { sentence: "The mountains lie ___ the river.", answer: "beyond", base: "beyond", hint: "b_____", ja: "～の向こうに、～を超えて", sentenceJa: "山々は川の向こうにある。" },
        { sentence: "I can't read this menu ___ my glasses.", answer: "without", base: "without", hint: "w______", ja: "～なしで", sentenceJa: "メガネなしではこのメニューを読めない。" },
        { sentence: "___ her sister, she enjoys sports.", answer: "unlike", base: "unlike", hint: "u_____", ja: "～と違って", sentenceJa: "姉（妹）と違って、彼女はスポーツを楽しむ。" },
        { sentence: "Call me ___ you need help.", answer: "whenever", base: "whenever", hint: "w_______", ja: "～するときはいつでも", sentenceJa: "助けが必要なときはいつでも私に電話してください。" },
        { sentence: "Please reply ___ three days.", answer: "within", base: "within", hint: "w_____", ja: "～以内に、～の中で", sentenceJa: "3   日以内に返信してください。" },
      ],
    },
    {
      name: "Day 10",
      items: [
        { sentence: "I'm just gonna ___ around.", answer: "travel", base: "travel", hint: "t_____", ja: "ちょっと離れた場所に移動する", sentenceJa: "ちょっとあちこち旅行するつもりです。" },
        { sentence: "Always ___ your car doors so people won't steal your things.", answer: "lock", base: "lock", hint: "l___", ja: "に鍵をかける", sentenceJa: "他人に物を盗まれないように、車のドアは常にロックしてください。" },
        { sentence: "His riddle really ___ me.", answer: "confused", base: "confuse", hint: "c______", ja: "を混同する", sentenceJa: "彼のなぞなぞには本当に困惑しました。" },
        { sentence: "This box ___ everything I won at the fair.", answer: "contains", base: "contain", hint: "c______", ja: "を含む、を収容できる", sentenceJa: "この箱には私がフェアで勝ち取ったすべてが入っています。" },
        { sentence: "It is good to ___ your legs after sitting for a long time.", answer: "stretch", base: "stretch", hint: "s______", ja: "ストレッチをする、伸びる、を伸ばす", sentenceJa: "長時間座った後は足を伸ばすのも良いですね。" },
        { sentence: "Every year my company ___ one person Employee of the Year.", answer: "awards", base: "award", hint: "a____", ja: "（賞など）を与える", sentenceJa: "私の会社では毎年、年間最優秀従業員 1 名を表彰しています。" },
        { sentence: "There are two large men ___ the doors.", answer: "guarding", base: "guard", hint: "g____", ja: "を守る、を監視する", sentenceJa: "大柄な男性2人がドアを見張っています。" },
        { sentence: "___ pest animals and releasing them somewhere else is more humane than killing them.", answer: "trapping", base: "trap", hint: "t___", ja: "を閉じ込める、（動物）を罠で捕らえる", sentenceJa: "害獣を捕まえて別の場所に放すことは、殺すより人道的です。" },
        { sentence: "I want to ___ flowers in my garden this year.", answer: "plant", base: "plant", hint: "p____", ja: "を植える、（種）をまく", sentenceJa: "今年は庭に花を植えたいと思っています。" },
        { sentence: "I need to ___ my room to make it easier to find things.", answer: "organize", base: "organize", hint: "o_______", ja: "を主催する、を組織する", sentenceJa: "物を探しやすいように部屋を整理する必要があります。" },
        { sentence: "Scientists are trying to ___ a better kind of battery.", answer: "invent", base: "invent", hint: "i_____", ja: "を発明する", sentenceJa: "科学者たちは、より優れた種類のバッテリーを発明しようとしています。" },
        { sentence: "I ___ what I should have for breakfast tomorrow.", answer: "wonder", base: "wonder", hint: "w_____", ja: "～かなと思う", sentenceJa: "明日の朝食は何にしようかな。" },
        { sentence: "Games where you collect and ___ cards are very popular.", answer: "trade", base: "trade", hint: "t____", ja: "を交換する、貿易する", sentenceJa: "カードを集めて交換するゲームは非常に人気があります。" },
        { sentence: "He will probably ___ another 6 inches.", answer: "grow", base: "grow", hint: "g___", ja: "成長する、増大する、を栽培する", sentenceJa: "おそらくあと6インチは伸びるだろう。" },
        { sentence: "I ___ my fingernails too much.", answer: "bite", base: "bite", hint: "b___", ja: "を噛む", sentenceJa: "爪を噛みすぎてしまいます。" },
        { sentence: "I don’t ___ that my neighbors are a bit loud sometimes, they’re nice people.", answer: "mind", base: "mind", hint: "m___", ja: "を気にする（嫌がる）、に気を付ける", sentenceJa: "隣人は時々少しうるさいですが、彼らは良い人たちなので気にしません。" },
        { sentence: "I ___ that I will not tell a lie.", answer: "promise", base: "promise", hint: "p______", ja: "を約束する", sentenceJa: "嘘はつかないと約束します。" },
        { sentence: "That chair’s leg is broken, will you ___ it please?", answer: "fix", base: "fix", hint: "f__", ja: "を修理する、を固定する", sentenceJa: "その椅子の脚が壊れているので、直してくれませんか？" },
        { sentence: "Bad things ___ sometimes.", answer: "happen", base: "happen", hint: "h_____", ja: "起こる、偶然～する", sentenceJa: "悪いことも時々起こります。" },
        { sentence: "One of my chores is to ___ the dog.", answer: "feed", base: "feed", hint: "f___", ja: "に食べ物を与える", sentenceJa: "私の家事の一つは犬に餌をあげることです。" },
      ],
    },
    {
      name: "Day 11",
      items: [
        { sentence: "I often ___ deer in the fall.", answer: "hunt", base: "hunt", hint: "h___", ja: "探し求める、を狩る", sentenceJa: "私は秋によく鹿を狩ります。" },
        { sentence: "___ the power cord to the computer so I can turn it on.", answer: "connect", base: "connect", hint: "c______", ja: "をつなぐ", sentenceJa: "電源を入れられるように、電源コードをコンピューターにつないで。" },
        { sentence: "My siblings and I always ___ for who gets to sit in the front seat.", answer: "compete", base: "compete", hint: "c______", ja: "競争する", sentenceJa: "私と兄弟はいつも誰が前の席に座れるか競い合います。" },
        { sentence: "___ out the candles on your birthday cake.", answer: "blow", base: "blow", hint: "b___", ja: "（風が）吹く、に息を吹きかける", sentenceJa: "誕生日ケーキのろうそくを吹き消して。" },
        { sentence: "We will ___ our destination in 10 minutes.", answer: "reach", base: "reach", hint: "r____", ja: "に到着する", sentenceJa: "10分以内に目的地に到着します。" },
        { sentence: "People usually ___ when they reach 65 years old.", answer: "retire", base: "retire", hint: "r_____", ja: "引退する", sentenceJa: "通常、人は65歳になると退職します。" },
        { sentence: "Scientists are always trying to ___ new kinds of medicine.", answer: "create", base: "create", hint: "c_____", ja: "を創造する", sentenceJa: "科学者は常に新しい種類の薬を開発しようとしています。" },
        { sentence: "We hired wait staff to ___ dinner at the party.", answer: "serve", base: "serve", hint: "s____", ja: "を出す、に給仕する、に仕える", sentenceJa: "私たちはパーティーで夕食を提供するために給仕スタッフを雇った。" },
        { sentence: "Can you ___ on the lights please?", answer: "switch", base: "switch", hint: "s_____", ja: "をスイッチで切り替える、を変える、転換する", sentenceJa: "ライトをつけてもらえますか？" },
        { sentence: "It's important to ___ for your local representatives as well as national ones.", answer: "vote", base: "vote", hint: "v___", ja: "投票する、を投票で決める", sentenceJa: "国の代表だけでなく地方の代表にも投票することが重要です。" },
        { sentence: "I always ___ up early, even on the weekends.", answer: "wake", base: "wake", hint: "w___", ja: "目を覚ます（wake A upで）Aを起こす", sentenceJa: "私は週末であっても、いつも早起きします。" },
        { sentence: "I will ___ working after a short break.", answer: "continue", base: "continue", hint: "c_______", ja: "を続ける、続く", sentenceJa: "少し休憩した後、作業を続けます。" },
        { sentence: "I was ___ by heavy traffic this morning.", answer: "delayed", base: "delay", hint: "d____", ja: "を遅らせる、を延期する", sentenceJa: "今朝大渋滞で遅れてしまいました。" },
        { sentence: "I can’t find a place to ___ the car.", answer: "park", base: "park", hint: "p___", ja: "を駐車する", sentenceJa: "車を駐車する場所が見つかりません。" },
        { sentence: "If we work hard, we can ___ the project quickly.", answer: "complete", base: "complete", hint: "c_______", ja: "を達成する、を完全なものにする", sentenceJa: "私たちが一生懸命働けば、プロジェクトをすぐに完了することができます。" },
        { sentence: "Babies ___ on their mothers to feed and bathe them.", answer: "depend", base: "depend", hint: "d_____", ja: "頼る、依存する", sentenceJa: "赤ちゃんは母親に食事と入浴を頼っています。" },
        { sentence: "I hope the school ___ my application.", answer: "accepts", base: "accept", hint: "a_____", ja: "を受け入れる、を受け取る", sentenceJa: "学校が私の申請を受け入れてくれることを願っています。" },
        { sentence: "I ___ to make the sale.", answer: "failed", base: "fail", hint: "f___", ja: "に不合格になる、失敗する", sentenceJa: "販売に失敗してしまいました。" },
        { sentence: "My phone rang, but I didn't want to talk to anyone so I just ___ it.", answer: "ignored", base: "ignore", hint: "i_____", ja: "を無視する", sentenceJa: "電話が鳴ったけど、誰とも話したくないので無視しました。" },
        { sentence: "I would like to ___ a song for the musician to play.", answer: "request", base: "request", hint: "r______", ja: "を要請する", sentenceJa: "ミュージシャンに演奏してもらう曲をリクエストしたいのですが。" },
      ],
    },
    {
      name: "Day 12",
      items: [
        { sentence: "I’ve been ___ for a new place to live.", answer: "searching", base: "search", hint: "s_____", ja: "捜す", sentenceJa: "新しく住む場所を探しています。" },
        { sentence: "I ___ myself playing soccer yesterday.", answer: "hurt", base: "hurt", hint: "h___", ja: "を傷つける、痛む", sentenceJa: "昨日サッカーをしていて怪我をしました。" },
        { sentence: "Small children should have lidded cups so they don't ___ their drinks.", answer: "spill", base: "spill", hint: "s____", ja: "をこぼす、こぼれる", sentenceJa: "小さなお子様には、飲み物をこぼさないように蓋付きのカップが必要です。" },
        { sentence: "When I was a child I liked to ___ that I was a superhero.", answer: "imagine", base: "imagine", hint: "i______", ja: "を想像する", sentenceJa: "子供の頃、私は自分がスーパーヒーローになったと想像するのが好きでした。" },
        { sentence: "I'm sorry I forgot to ___ to your message.", answer: "reply", base: "reply", hint: "r____", ja: "返事をする、答える", sentenceJa: "メッセージに返信するのを忘れてしまい申し訳ありません。" },
        { sentence: "I always ___ my son to try again if he fails.", answer: "encourage", base: "encourage", hint: "e________", ja: "を励ます", sentenceJa: "私はいつも息子に、失敗してももう一度挑戦するよう勧めています。" },
        { sentence: "I’m waiting for the mailman to ___ my package.", answer: "deliver", base: "deliver", hint: "d______", ja: "を配達する", sentenceJa: "郵便屋さんが荷物を届けるのを待っています。" },
        { sentence: "He's very lucky to have ___ the car crash.", answer: "survived", base: "survive", hint: "s______", ja: "を生き残る", sentenceJa: "彼は自動車事故から生き残れたのはとても幸運だ。" },
        { sentence: "I don’t own my house, I ___ from a landlord.", answer: "rent", base: "rent", hint: "r___", ja: "を借りる、を貸す", sentenceJa: "私は自分の家を持っていません、家主から借りています。" },
        { sentence: "We will ___ what to do later.", answer: "decide", base: "decide", hint: "d_____", ja: "を決心する", sentenceJa: "どうするかは後で決めます。" },
        { sentence: "The siren is meant to ___ people of an incoming tsunami.", answer: "warn", base: "warn", hint: "w___", ja: "に警告する", sentenceJa: "サイレンは津波の到来を人々に警告するためのものです。" },
        { sentence: "The restaurant is very busy tonight, we should ___ a table.", answer: "reserve", base: "reserve", hint: "r______", ja: "を予約する、を取っておく", sentenceJa: "今夜のレストランはとても忙しいので、テーブルを予約したほうがいいでしょう。" },
        { sentence: "I think this is a dead end, let's ___ back.", answer: "turn", base: "turn", hint: "t___", ja: "進路を変える、変わる、を曲がる", sentenceJa: "ここは行き止まりだと思うので引き返そう。" },
        { sentence: "I wonder what time the sun will ___ tomorrow?", answer: "rise", base: "rise", hint: "r___", ja: "（太陽などが）昇る、（価格・温度などが）上がる", sentenceJa: "明日は何時に日が昇るだろうか？" },
        { sentence: "He didn’t ___ the last meeting for some reason.", answer: "attend", base: "attend", hint: "a_____", ja: "に出席する、の世話をする", sentenceJa: "彼は何らかの理由で前回の会議に出席しませんでした。" },
        { sentence: "Some men managed to ___ prison yesterday.", answer: "escape", base: "escape", hint: "e_____", ja: "逃げる", sentenceJa: "何人かの男が昨日、刑務所から脱走することに成功しました。" },
        { sentence: "I never learned how to properly ___ a football.", answer: "throw", base: "throw", hint: "t____", ja: "を投げる", sentenceJa: "私はサッカーの正しい投げ方を学んだことがありません。" },
        { sentence: "I will ___ a blanket on the couch to make it more comfortable.", answer: "lay", base: "lay", hint: "l__", ja: "を横たえる、を敷く", sentenceJa: "もっと快適にするためにソファに毛布を敷きます。" },
        { sentence: "I had to ___ the driver to where I was going because he didn’t know the way.", answer: "guide", base: "guide", hint: "g____", ja: "を案内する、を指導する", sentenceJa: "運転手が道を知らなかったため、私は運転手を目的地まで案内しなければなりませんでした。" },
        { sentence: "I didn’t ___ that I had spilled my drink until my sleeve got wet.", answer: "notice", base: "notice", hint: "n_____", ja: "に気づく", sentenceJa: "袖が濡れるまで飲み物をこぼしたことに気づきませんでした。" },
      ],
    },
    {
      name: "Day 13",
      items: [
        { sentence: "If you want more information, ___ to the source I listed.", answer: "refer", base: "refer", hint: "r____", ja: "言及する、参照する", sentenceJa: "さらに詳しい情報が必要な場合は、私がリストしたソースを参照してください。" },
        { sentence: "I ___ you helping me out.", answer: "appreciate", base: "appreciate", hint: "a_________", ja: "を感謝する", sentenceJa: "助けてくれてありがとう。" },
        { sentence: "I saw a dog ___ someone at the park.", answer: "attack", base: "attack", hint: "a_____", ja: "を攻撃する", sentenceJa: "私は公園で犬が人を襲っているのを見ました。" },
        { sentence: "In the movie, they ___ the jungle and find hidden treasure.", answer: "explore", base: "explore", hint: "e______", ja: "を探検する、を調査する", sentenceJa: "映画では、彼らはジャングルを探索し、隠された宝物を見つけます。" },
        { sentence: "I want to ___ my English speaking skills.", answer: "improve", base: "improve", hint: "i______", ja: "を改良（改善）する、よくなる", sentenceJa: "英語のスピーキングスキルを向上させたいです。" },
        { sentence: "The islands of Japan ___ the four main islands and many smaller ones.", answer: "include", base: "include", hint: "i______", ja: "を含む", sentenceJa: "日本の島々には、主要な 4 つの島と多くの小さな島が含まれます。" },
        { sentence: "I would ___ you to think carefully about what you say to her while she’s upset.", answer: "advise", base: "advise", hint: "a_____", ja: "に忠告する", sentenceJa: "彼女が動揺しているときに彼女に何を言うか、慎重に考えることをお勧めします。" },
        { sentence: "Can you ___ the table a little bit, please?", answer: "wipe", base: "wipe", hint: "w___", ja: "拭く", sentenceJa: "テーブルを少し拭いてもらえますか？" },
        { sentence: "I don't ___ curry, but I don't really like it either.", answer: "dislike", base: "dislike", hint: "d______", ja: "を嫌う", sentenceJa: "カレーは嫌いではないですが、あまり好きでもありません。" },
        { sentence: "A cat suddenly ___ from behind the wall.", answer: "appeared", base: "appear", hint: "a_____", ja: "出現する、のように見える", sentenceJa: "突然壁の向こうから猫が現れた。" },
        { sentence: "He ___ his car into a tree, but he wasn't injured.", answer: "crashed", base: "crash", hint: "c____", ja: "衝突する", sentenceJa: "彼は車を木に衝突させたが、怪我はなかった。" },
        { sentence: "I will ___ food soon.", answer: "order", base: "order", hint: "o____", ja: "注文する、命じる", sentenceJa: "すぐに食べ物を注文します。" },
        { sentence: "I had to ___ for him at the train station.", answer: "wait", base: "wait", hint: "w___", ja: "待つ", sentenceJa: "私は駅で彼を待たなければなりませんでした。" },
        { sentence: "The court ___ him not guilty of the crime.", answer: "judged", base: "judge", hint: "j____", ja: "を判断する、裁く", sentenceJa: "裁判所は彼に無罪の判決を下した。" },
        { sentence: "I had to ___ a whole speech for my audition.", answer: "memorize", base: "memorize", hint: "m_______", ja: "を暗記する、を記憶する", sentenceJa: "オーディションのためにスピーチを丸暗記しなければなりませんでした。" },
        { sentence: "Be careful not to ___ your glass.", answer: "drop", base: "drop", hint: "d___", ja: "を落とす、を下す、（物が）突然落ちる", sentenceJa: "グラスを落とさないように気をつけて。" },
        { sentence: "It is my dream to ___ a new species of animal.", answer: "discover", base: "discover", hint: "d_______", ja: "を発見する", sentenceJa: "新種の動物を発見するのが私の夢です。" },
        { sentence: "I ___ I had time to go on vacation this month.", answer: "wish", base: "wish", hint: "w___", ja: "～であればいいのに（と思う）、を願う", sentenceJa: "今月休暇に行く時間があればいいのにと思います。" },
        { sentence: "When will the train ___ at the station?", answer: "arrive", base: "arrive", hint: "a_____", ja: "到着する", sentenceJa: "電車はいつ駅に到着しますか?" },
        { sentence: "___ on the door before you enter a room.", answer: "knock", base: "knock", hint: "k____", ja: "ノックする、（こぶしなどで）たたく、をぶつける", sentenceJa: "部屋に入る前にドアをノックして。" },
      ],
    },
    {
      name: "Day 15",
      items: [
        { sentence: "These new shoes ___ perfectly.", answer: "fit", base: "fit", hint: "f__", ja: "に（サイズが）ぴったり合う、に適している", sentenceJa: "この新しい靴は完璧にフィットします。" },
        { sentence: "I don’t want to ___ my phone.", answer: "lose", base: "lose", hint: "l___", ja: "を失う、負ける", sentenceJa: "携帯電話を失いたくないのです。" },
        { sentence: "She ___ me to call her after work.", answer: "expects", base: "expect", hint: "e_____", ja: "を予期する、を期待する", sentenceJa: "彼女は私が仕事の後に電話することを期待しています。" },
        { sentence: "Don’t ___ the artwork.", answer: "touch", base: "touch", hint: "t____", ja: "に触れる、を感動させる", sentenceJa: "作品には触れないで。" },
        { sentence: "I ___ you try the fish, it’s delicious.", answer: "recommend", base: "recommend", hint: "r________", ja: "を推薦する、を勧める", sentenceJa: "魚は美味しいのでぜひ食べてみることをお勧めします。" },
        { sentence: "I want to ___ my girlfriend someday.", answer: "marry", base: "marry", hint: "m____", ja: "と結婚する", sentenceJa: "いつか彼女と結婚したいです。" },
        { sentence: "It can be hard to ___ someone you don't really know.", answer: "trust", base: "trust", hint: "t____", ja: "を信用（信頼）する", sentenceJa: "よく知らない人を信頼するのは難しいかもしれません。" },
        { sentence: "My child is finally old enough to ___ himself.", answer: "dress", base: "dress", hint: "d____", ja: "服を着る、に服を着せる", sentenceJa: "私の子供もようやく自分で服を着られる年齢になりました。" },
        { sentence: "My friend is going to ___ in the next school play.", answer: "act", base: "act", hint: "a__", ja: "を演じる、行動する", sentenceJa: "私の友達は次の学校の演劇に出演する予定です。" },
        { sentence: "I like to ___ mountains on the weekends.", answer: "climb", base: "climb", hint: "c____", ja: "を登る", sentenceJa: "私は週末に山に登るのが好きです。" },
        { sentence: "I was bored so I called my friend to ___.", answer: "chat", base: "chat", hint: "c___", ja: "おしゃべりする、雑談する", sentenceJa: "退屈だったので、友人に電話しておしゃべりしました。" },
        { sentence: "Do you ___ in Santa Clause?", answer: "believe", base: "believe", hint: "b______", ja: "を信じる", sentenceJa: "サンタクロースを信じますか?" },
        { sentence: "You ___ wanting to go surfing earlier, so I'm going to take you for your birthday.", answer: "mentioned", base: "mention", hint: "m______", ja: "に言及する、を述べる", sentenceJa: "先ほどサーフィンに行きたいと言っていたので、誕生日に連れて行きます。" },
        { sentence: "Aluminum ___ at 660 degrees celsius.", answer: "melts", base: "melt", hint: "m___", ja: "溶ける、を溶かす", sentenceJa: "アルミニウムは摂氏660度で溶けます。" },
        { sentence: "The phone ___ all day on Saturdays.", answer: "rings", base: "ring", hint: "r___", ja: "鳴る、を鳴らす", sentenceJa: "土曜日は一日中電話が鳴ります。" },
        { sentence: "Doctors usually ___ in a certain field of medicine.", answer: "specialize", base: "specialize", hint: "s_________", ja: "専門とする、専攻する", sentenceJa: "医師は通常、特定の医学分野を専門としています。" },
        { sentence: "I will ___ for the dinner.", answer: "pay", base: "pay", hint: "p__", ja: "支払う", sentenceJa: "夕食代は私が払います。" },
        { sentence: "Soaking in the hot spring ___ me after a hard day's work.", answer: "refreshed", base: "refresh", hint: "r______", ja: "を元気づける、の気分をさわやかにする", sentenceJa: "温泉に浸かると、一日の忙しい仕事の後にリフレッシュできました。" },
        { sentence: "I ___ a letter in the mail.", answer: "received", base: "receive", hint: "r______", ja: "を受け取る", sentenceJa: "郵便で手紙を受け取りました。" },
        { sentence: "___ the button to call the elevator.", answer: "press", base: "press", hint: "p____", ja: "を押す、にアイロンをかける", sentenceJa: "エレベーターを呼ぶために、ボタンを押して。" },
      ],
    },
    {
      name: "Day 16",
      items: [
        { sentence: "We will ___ our rival team at the match tomorrow.", answer: "face", base: "face", hint: "f___", ja: "に直面する、の方を向く", sentenceJa: "私たちは明日の試合でライバルチームと対戦します。" },
        { sentence: "I don’t want my dog to ___.", answer: "die", base: "die", hint: "d__", ja: "死ぬ", sentenceJa: "うちの犬を死なせたくない。" },
        { sentence: "You don't have to ___ for being late.", answer: "apologize", base: "apologize", hint: "a________", ja: "謝る", sentenceJa: "遅れたことを謝る必要はありません。" },
        { sentence: "I don’t want to ___ my parents so I’m going to finish all my schoolwork.", answer: "disappoint", base: "disappoint", hint: "d_________", ja: "失望する、を失望させる", sentenceJa: "両親を失望させたくないので、学校の勉強はすべて終わらせるつもりです。" },
        { sentence: "She got to ___ a famous actor.", answer: "interview", base: "interview", hint: "i________", ja: "にインタビューする、と面接する", sentenceJa: "彼女は有名な俳優にインタビューすることになった。" },
        { sentence: "I want to find a gallery to ___ my art in.", answer: "display", base: "display", hint: "d______", ja: "を展示する、を示す", sentenceJa: "自分の作品を展示できるギャラリーを見つけたいです。" },
        { sentence: "Firefighters often ___ people from burning buildings.", answer: "rescue", base: "rescue", hint: "r_____", ja: "を救助する", sentenceJa: "消防士は燃えている建物から人々を救出することがよくあります。" },
        { sentence: "Sushi is sometimes ___ in seaweed.", answer: "wrapped", base: "wrap", hint: "w___", ja: "を包む、を巻き付ける", sentenceJa: "寿司は海苔で巻かれることもあります。" },
        { sentence: "I like to ___ the internet in my spare time.", answer: "surf", base: "surf", hint: "s___", ja: "（ホームページなどを）見て回る、サーフィンをする", sentenceJa: "私は暇なときにインターネットをサーフィンするのが好きです。" },
        { sentence: "My family is going to ___ to California soon.", answer: "move", base: "move", hint: "m___", ja: "引っ越す、を動かす、を感動させる", sentenceJa: "私の家族はもうすぐカリフォルニアに引っ越します。" },
        { sentence: "I saw my friend across the store and ___ to them.", answer: "waved", base: "wave", hint: "w___", ja: "手を振る、（旗など）を振る", sentenceJa: "私は店の向こう側で友人を見つけて手を振りました。" },
        { sentence: "If a question is too difficult to answer you should ___ it.", answer: "skip", base: "skip", hint: "s___", ja: "を抜かす、跳ねる", sentenceJa: "質問が難しすぎて答えることができない場合は、スキップしてください。" },
        { sentence: "This door doesn’t ___ to actually open, I think it’s fake.", answer: "seem", base: "seem", hint: "s___", ja: "のようだ、のように見える", sentenceJa: "このドアは実際には開かないようです、偽物だと思います。" },
        { sentence: "The policemen ___ the robber.", answer: "arrested", base: "arrest", hint: "a_____", ja: "を逮捕する", sentenceJa: "警察官はその強盗を逮捕した。" },
        { sentence: "She ___ me with a gift on my birthday.", answer: "surprised", base: "surprise", hint: "s_______", ja: "驚く、を驚かせる", sentenceJa: "誕生日に彼女がプレゼントで私を驚かせました。" },
        { sentence: "I can’t ___ this over my head, it’s too heavy.", answer: "lift", base: "lift", hint: "l___", ja: "を持ち上げる", sentenceJa: "これを頭の上に持ち上げることはできません、重すぎます。" },
        { sentence: "We need to ___ pollution to stop global warming.", answer: "reduce", base: "reduce", hint: "r_____", ja: "を減らす、減る", sentenceJa: "地球温暖化を止めるには汚染を減らす必要があります。" },
        { sentence: "I made some money ___ over the summer.", answer: "babysitting", base: "babysit", hint: "b______", ja: "（子供）の世話をする、子供を世話する", sentenceJa: "夏の間ベビーシッターをして少しお金を稼ぎました。" },
        { sentence: "In my new car, you ___ a button to start the engine.", answer: "push", base: "push", hint: "p___", ja: "を押す", sentenceJa: "私の新しい車では、ボタンを押してエンジンを始動します。" },
        { sentence: "I ___ at a soup kitchen on the weekends.", answer: "volunteer", base: "volunteer", hint: "v________", ja: "ボランティアをする、を自発的に引き受ける", sentenceJa: "私は週末に炊き出しのボランティアをしています。" },
      ],
    },
    {
      name: "Day 17",
      items: [
        { sentence: "___ the water up to the marked line.", answer: "pour", base: "pour", hint: "p___", ja: "を注ぐ、（雨が）激しく降る", sentenceJa: "水を標線まで注いで。" },
        { sentence: "Please ___ through the front door.", answer: "enter", base: "enter", hint: "e____", ja: "に入る、に参加（出場）する", sentenceJa: "正面玄関から入って。" },
        { sentence: "Hokkaido ___ a lot of Japan’s food.", answer: "produces", base: "produce", hint: "p______", ja: "を生産する、を引き起こす", sentenceJa: "北海道は日本の食材をたくさん生産しています。" },
        { sentence: "I have never tried to ___ a baseball bat.", answer: "swing", base: "swing", hint: "s____", ja: "を揺らす、揺れる", sentenceJa: "私は野球のバットを振ろうとしたことがありません。" },
        { sentence: "I can ___ my bedroom lights with a remote.", answer: "control", base: "control", hint: "c______", ja: "を管理する、を支配する、を制御する", sentenceJa: "リモコンで寝室の照明を操作できます。" },
        { sentence: "I think I will ___ John to my birthday party.", answer: "invite", base: "invite", hint: "i_____", ja: "を招待する", sentenceJa: "ジョンを私の誕生日パーティーに招待しようと思います。" },
        { sentence: "A river ___ through the middle of town.", answer: "flows", base: "flow", hint: "f___", ja: "流れる", sentenceJa: "町の真ん中を川が流れています。" },
        { sentence: "Let’s ___ our plans for the weekend.", answer: "discuss", base: "discuss", hint: "d______", ja: "について議論（討論）する", sentenceJa: "週末の計画について話し合おう。" },
        { sentence: "I need to ___ my study materials to prepare for the test.", answer: "review", base: "review", hint: "r_____", ja: "を復習する、をよく調べる", sentenceJa: "試験に備えて教材を復習する必要があります。" },
        { sentence: "I ___ not going to college when I had the chance.", answer: "regret", base: "regret", hint: "r_____", ja: "を後悔する", sentenceJa: "チャンスがあったのに大学に行かなかったことを後悔しています。" },
        { sentence: "I ___ my new clock to the current time.", answer: "set", base: "set", hint: "s__", ja: "を合わせる、を置く", sentenceJa: "新しい時計を現在時刻に設定しました。" },
        { sentence: "Fishing too much can ___ the food chain in the ocean.", answer: "upset", base: "upset", hint: "u____", ja: "動揺する、を動転させる", sentenceJa: "釣りをしすぎると海の食物連鎖が崩れる可能性があります。" },
        { sentence: "I will ___ you to have one cookie before dinner.", answer: "allow", base: "allow", hint: "a____", ja: "(allow O to doで)Oが～するのを許す", sentenceJa: "夕食前にクッキーを1枚食べさせます。" },
        { sentence: "I will ___ you when I am ready to meet.", answer: "contact", base: "contact", hint: "c______", ja: "と連絡を取る、と接触する", sentenceJa: "会う準備ができたら連絡します。" },
        { sentence: "I don't like how animals ___ on factory farms.", answer: "suffer", base: "suffer", hint: "s_____", ja: "苦しむ、病気にかかる、（損害・損傷など）を受ける", sentenceJa: "工場式畜産で動物が苦しむのを見るのは嫌です。" },
        { sentence: "Let’s ___ wood for the fire.", answer: "gather", base: "gather", hint: "g_____", ja: "集まる、を集める", sentenceJa: "たき火用の薪を集めよう。" },
        { sentence: "I am going to ___ home after I complete this errand.", answer: "return", base: "return", hint: "r_____", ja: "帰る、戻る、を返す", sentenceJa: "この用事を終えたら家に帰るつもりです。" },
        { sentence: "Her flowing dress ___ a lot of attention on the red carpet.", answer: "attracted", base: "attract", hint: "a______", ja: "の心をとらえる、（注意・興味などを）引く、魅了される", sentenceJa: "流れるようなドレスがレッドカーペットで注目を集めた。" },
        { sentence: "They ___ how much of some products you can buy at once.", answer: "limit", base: "limit", hint: "l____", ja: "を制限する", sentenceJa: "一部の商品については一度に購入できる量が制限されています。" },
        { sentence: "The water filter is old, it’s time to ___ it.", answer: "replace", base: "replace", hint: "r______", ja: "を取り換える", sentenceJa: "浄水フィルターが古いので交換時期です。" },
      ],
    },
    {
      name: "Day 18",
      items: [
        { sentence: "I need to ___ my clothes.", answer: "change", base: "change", hint: "c_____", ja: "を変える、変わる", sentenceJa: "服を着替える必要があります。" },
        { sentence: "This gum ___ like black licorice.", answer: "tastes", base: "taste", hint: "t____", ja: "の味がする、を味わう", sentenceJa: "このガムは黒甘草のような味がします。" },
        { sentence: "I ___ you’re my new partner for this project?", answer: "suppose", base: "suppose", hint: "s______", ja: "（be supposed to doで）～することになっている、と仮定する", sentenceJa: "あなたがこのプロジェクトの私の新しいパートナーだと思いますか？" },
        { sentence: "Some heaters use electricity and some ___ wood for warmth.", answer: "burn", base: "burn", hint: "b___", ja: "燃える、を燃やす", sentenceJa: "ヒーターには電気を使用するものと、木材を燃やして暖をとるものがあります。" },
        { sentence: "I ___ him when he called me names.", answer: "hit", base: "hit", hint: "h__", ja: "を打つ、にぶつかる", sentenceJa: "彼が私を悪口で呼んだとき、私は彼を殴りました。" },
        { sentence: "They will ___ a convention in that arena next month.", answer: "hold", base: "hold", hint: "h___", ja: "を開催する、を持つ", sentenceJa: "彼らは来月そのアリーナで大会を開催する予定です。" },
        { sentence: "I will ___ your offer, but I can't promise that I will accept.", answer: "consider", base: "consider", hint: "c_______", ja: "についてよく考える、を熟考する", sentenceJa: "あなたの申し出を検討しますが、受け入れるかどうかは約束できません。" },
        { sentence: "I don’t know that word, let me ___ the dictionary.", answer: "check", base: "check", hint: "c____", ja: "確かめる、調べる", sentenceJa: "私はその言葉を知りません、辞書を調べさせてください。" },
        { sentence: "I need to ___ the number of calories I eat.", answer: "decrease", base: "decrease", hint: "d_______", ja: "減少する、を減少させる", sentenceJa: "摂取カロリーを減らす必要があります。" },
        { sentence: "I didn't think he would ___ in his daring stunt, but he landed it perfectly.", answer: "succeed", base: "succeed", hint: "s______", ja: "成功する、継承する", sentenceJa: "彼の大胆なスタントが成功するとは思わなかったが、彼はそれを完璧に決めた。" },
        { sentence: "Things denser than water will ___ while things less dense will float.", answer: "sink", base: "sink", hint: "s___", ja: "沈む、を沈める", sentenceJa: "水より密度の高いものは沈みますが、密度が低いものは浮きます。" },
        { sentence: "I wanted to ___ a picture, but my printer is out of ink.", answer: "print", base: "print", hint: "p____", ja: "を印刷する", sentenceJa: "写真を印刷したいのですが、プリンターのインクがなくなりました。" },
        { sentence: "It can be hard to ___ your feelings sometimes.", answer: "express", base: "express", hint: "e______", ja: "を表現する", sentenceJa: "自分の気持ちを表現するのが難しいこともあります。" },
        { sentence: "It's my responsibility to ___ the flag every day after school.", answer: "lower", base: "lower", hint: "l____", ja: "を下げる", sentenceJa: "毎日放課後に旗を降ろすのは私の責任です。" },
        { sentence: "I love to ___ puzzles.", answer: "solve", base: "solve", hint: "s____", ja: "を解決する", sentenceJa: "私はパズルを解くのが大好きです。" },
        { sentence: "If you ___ too much salt, the cake won’t come out right.", answer: "add", base: "add", hint: "a__", ja: "を加える", sentenceJa: "塩を入れすぎるとケーキがうまく焼けなくなります。" },
        { sentence: "I like to ___ cakes for my friends’ birthdays.", answer: "bake", base: "bake", hint: "b___", ja: "を焼く", sentenceJa: "私は友達の誕生日にケーキを焼くのが好きです。" },
        { sentence: "I ___ giving him the car keys.", answer: "remember", base: "remember", hint: "r_______", ja: "を覚えている", sentenceJa: "彼に車のキーを渡したのを覚えています。" },
        { sentence: "I will ___ this poster on the wall.", answer: "hang", base: "hang", hint: "h___", ja: "をつるす、を掛ける", sentenceJa: "このポスターを壁に掛けます。" },
      ],
    },
    {
      name: "Day 19",
      items: [
        { sentence: "I can't ___ the difference.", answer: "tell", base: "tell", hint: "t___", ja: "伝える、見分ける", sentenceJa: "違いが分かりません。" },
        { sentence: "I don't ___ a car, so I need to take a[the] bus.", answer: "own", base: "own", hint: "o__", ja: "所有する、自分のものとして持っている", sentenceJa: "私は車を持っていないので、バスに乗る必要があります。" },
        { sentence: "The product didn't ___ my expectation.", answer: "meet", base: "meet", hint: "m___", ja: "会う、満たす、間に合う", sentenceJa: "その製品は私の期待を満たしていませんでした。" },
        { sentence: "This link ___ to a different website.", answer: "leads", base: "lead", hint: "l___", ja: "導く、飛ぶ（ネット用語）", sentenceJa: "このリンクをクリックすると別のウェブサイトに移動します。" },
        { sentence: "I like to ___ on my day before I go to bed.", answer: "reflect", base: "reflect", hint: "r______", ja: "〜を反射する、〜を反映する、振り返る", sentenceJa: "私は寝る前にその日を振り返るのが好きです。" },
        { sentence: "___ your hand if you have a question.", answer: "raise", base: "raise", hint: "r____", ja: "上げる、育てる", sentenceJa: "質問があるなら手を挙げて。" },
        { sentence: "I ___ you one.", answer: "owe", base: "owe", hint: "o__", ja: "借りている、〜のおかげである", sentenceJa: "借りがあります。" },
        { sentence: "She ___ her own restaurant in the city.", answer: "runs", base: "run", hint: "r__", ja: "走る、経営する、動く、流れる", sentenceJa: "彼女は市内で自分のレストランを経営しています。" },
        { sentence: "You can ___ on me.", answer: "count", base: "count", hint: "c____", ja: "〜を数える、頼りにする、価値がある\n", sentenceJa: "私に任せて。" },
        { sentence: "Please ___ these items by color.", answer: "sort", base: "sort", hint: "s___", ja: "分類する", sentenceJa: "これらの品物を色別に分けて。" },
        { sentence: "This beef  jerky ___ until next month.", answer: "lasts", base: "last", hint: "l___", ja: "持続する、続く", sentenceJa: "このビーフジャーキーは来月まで続きます。" },
        { sentence: "You ___ a break.", answer: "deserve", base: "deserve", hint: "d______", ja: "〜に値する、相応しい", sentenceJa: "あなたには休憩が必要です。" },
        { sentence: "Have you ever ___ a serious crime?", answer: "committed", base: "commit", hint: "c_____", ja: "犯罪を犯す、本気で取り組む", sentenceJa: "重大な犯罪を犯したことがありますか？" },
        { sentence: "The company is ___ a new ad campaign next week.", answer: "launching", base: "launch", hint: "l_____", ja: "ロケットを打ち上げる、新しいことを始める", sentenceJa: "その会社は来週、新しい広告キャンペーンを開始します。" },
        { sentence: "I can't believe he ___ you.", answer: "dumped", base: "dump", hint: "d___", ja: "捨てる、恋人を振る", sentenceJa: "彼があなたを捨てたなんて信じられない。" },
        { sentence: "You ___ it was the best day of my entire life.", answer: "bet", base: "bet", hint: "b__", ja: "〜を賭ける、絶対〜だと確信する、もちろん", sentenceJa: "間違いなく、人生で最高の日でした。" },
        { sentence: "I couldn't ___ my phone yesterday.", answer: "locate", base: "locate", hint: "l_____", ja: "位置する、位置を特定する、見つける", sentenceJa: "昨日は携帯電話が見つかりませんでした。" },
        { sentence: "She's still ___ to find a job after graduation.", answer: "struggling", base: "struggle", hint: "s_______", ja: "もがく、必死に努力する、苦労する、頑張っている", sentenceJa: "彼女は卒業後も、仕事を見つけるのに苦労しています。" },
        { sentence: "Can you ___ the bill, please?", answer: "split", base: "split", hint: "s____", ja: "分ける", sentenceJa: "請求書を割り勘にしてもらえますか？" },
        { sentence: "The towel ___ all the spilled water.", answer: "absorbed", base: "absorb", hint: "a_____", ja: "吸収する、夢中になる", sentenceJa: "そのタオルはこぼれた水をすべて吸収しました。" },
      ],
    },
    {
      name: "Day 20",
      items: [
        { sentence: "I ___ to help, but he said it's fine.", answer: "offered", base: "offer", hint: "o____", ja: "申し出る、〜しようか？、提供する", sentenceJa: "私は手伝うと申し出ましたが、彼は大丈夫だと言いました。" },
        { sentence: "I ___ my phone when it got to 20 percent battery.", answer: "charged", base: "charge", hint: "c_____", ja: "充電する、請求する、担当する", sentenceJa: "バッテリー残量が20％になったとき、スマートフォンを充電しました。" },
        { sentence: "Let me ___ the picture to make sure I look good.", answer: "analyze", base: "analyze", hint: "a______", ja: "分析する", sentenceJa: "私が見栄えが良いかどうかを確認するために写真を分析させてください。" },
        { sentence: "He ___ every day at the gym.", answer: "trains", base: "train", hint: "t____", ja: "トレーニングする、鍛える、しつける、教育する", sentenceJa: "彼は毎日ジムでトレーニングします。" },
        { sentence: "It ___ to the back of your phone with magnets.", answer: "attaches", base: "attach", hint: "a_____", ja: "添付する、くっつく、貼る、愛着がある", sentenceJa: "携帯電話の背面に磁石で取り付けられます。" },
        { sentence: "Please ___ in the form.", answer: "fill", base: "fill", hint: "f___", ja: "満たす、記入する、代わりを務める", sentenceJa: "フォームに記入して。" },
        { sentence: "___ what!", answer: "guess", base: "guess", hint: "g____", ja: "推測する、〜かな", sentenceJa: "何だと思う！" },
        { sentence: "The sweater really ___ you.", answer: "suits", base: "suit", hint: "s___", ja: "似合う、都合がいい、〜に合う", sentenceJa: "そのセーターは本当にあなたに似合っています。" },
        { sentence: "He ___ his dog like a human.", answer: "treats", base: "treat", hint: "t____", ja: "扱う、奢る、ケアする", sentenceJa: "彼は自分の犬を人間のように扱います。" },
        { sentence: "We ___ the power to the house.", answer: "killed", base: "kill", hint: "k___", ja: "殺す、電気を切る、最高、気持ちを押し殺す、完食する", sentenceJa: "私たちは家の電気を止めました。" },
        { sentence: "She ___ herself in our plans without being invited.", answer: "involved", base: "involve", hint: "i______", ja: "含む、巻き込む", sentenceJa: "彼女は招待されていないのに、私たちの計画に関わってきました。" },
        { sentence: "He ___ his friendship by stealing money.", answer: "destroyed", base: "destroy", hint: "d______", ja: "破壊する、台無しにする\n", sentenceJa: "彼は金を盗んで友情を壊した。" },
        { sentence: "I've ___ in five meetings today.", answer: "packed", base: "pack", hint: "p___", ja: "荷造りする、詰める、満員になる", sentenceJa: "今日は5つの会議を詰め込みました。" },
        { sentence: "Can you ___ this note to the fridge?", answer: "stick", base: "stick", hint: "s____", ja: "くっつく、こだわる、（状態を）続ける、行き詰まる、動けなくなる（形容詞）", sentenceJa: "このメモを冷蔵庫に貼ってもらえますか？" },
        { sentence: "He ___ her face for any sign of emotion.", answer: "scanned", base: "scan", hint: "s___", ja: "〜をスキャンする、を注意深く調べる、〜をざっと見る", sentenceJa: "感情の表れがないか、彼女の顔をじっと見た。" },
        { sentence: "The team ___ to the next round.", answer: "advanced", base: "advance", hint: "a______", ja: "前進する、（トーナメントで）進出する", sentenceJa: "チームは次のラウンドに進みました。" },
        { sentence: "My computer ___.", answer: "froze", base: "freeze", hint: "f_____", ja: "凍る、〜を凍らせる、画面がフリーズする", sentenceJa: "コンピューターがフリーズしてしまいました。" },
        { sentence: "I'm going to ___ down for a bit.", answer: "lie", base: "lie", hint: "l__", ja: "嘘をつく、横になる、ある、潜んでいるイメージ", sentenceJa: "少し横になります。" },
        { sentence: "We had to ___ the trip because of the storm.", answer: "postpone", base: "postpone", hint: "p_______", ja: "延期する", sentenceJa: "嵐のため私たちは旅行を延期しなければなりませんでした。" },
        { sentence: "I think I ___ very quickly to life abroad.", answer: "adjusted", base: "adjust", hint: "a_____", ja: "〜を調整する、順応する", sentenceJa: "海外での生活にもすぐに適応できたと思います。" },
      ],
    },
    {
      name: "Day 22",
      items: [
        { sentence: "That makes ___.", answer: "sense", base: "sense", hint: "s____", ja: "感覚", sentenceJa: "それは理にかなっています。" },
        { sentence: "I'm making rest a ___.", answer: "priority", base: "priority", hint: "p_______", ja: "優先", sentenceJa: "休息を最優先にしています。" },
        { sentence: "Can you turn up the ___ a little, please?", answer: "volume", base: "volume", hint: "v_____", ja: "音量、本の巻、サイズ、体積、ボリューム量", sentenceJa: "音量を少し上げていただけますか？" },
        { sentence: "This shirt is made of really nice ___.", answer: "material", base: "material", hint: "m_______", ja: "材料、生地、素材、資料", sentenceJa: "このシャツは本当に素晴らしい素材でできています。" },
        { sentence: "I work in the marketing ___.", answer: "department", base: "department", hint: "d_________", ja: "デパートメント、部門、学部、省\n", sentenceJa: "私はマーケティング部門で働いています。" },
        { sentence: "I put my glasses back in the ___.", answer: "case", base: "case", hint: "c___", ja: "ケース、入れ物、事件、事例、場合", sentenceJa: "メガネをケースに戻しました。" },
        { sentence: "Can you clean the ___ of the room, please?", answer: "rest", base: "rest", hint: "r___", ja: "休む、余り、残り", sentenceJa: "部屋の残りの部分を掃除してもらえますか？" },
        { sentence: "Can we meet after your ___?", answer: "appointment", base: "appointment", hint: "a__________", ja: "約束、予約", sentenceJa: "約束の後に会えますか？" },
        { sentence: "My cat has a better ___ than I do.", answer: "diet", base: "diet", hint: "d___", ja: "食事、ダイエット", sentenceJa: "私の猫は私よりも良い食事をしています。" },
        { sentence: "Are you in a ___ right now?", answer: "relationship", base: "relationship", hint: "r___________", ja: "関係、恋愛、人間関係、物事の相関性", sentenceJa: "あなたは今付き合っていますか？" },
        { sentence: "What's the ___ of the game?", answer: "object", base: "object", hint: "o_____", ja: "物体、もの、目的、対象", sentenceJa: "ゲームの目的は何ですか?" },
        { sentence: "I love strawberry ___.", answer: "flavor", base: "flavor", hint: "f_____", ja: "味、性格、テイスト、雰囲気", sentenceJa: "イチゴ味が大好きです。" },
        { sentence: "Can you do me a ___?", answer: "favor", base: "favor", hint: "f____", ja: "親切な行為、好意、頼み事", sentenceJa: "お願いを聞いてもらえますか？" },
        { sentence: "He lives beyond his ___.", answer: "means", base: "means", hint: "m____", ja: "手段、方法、財力", sentenceJa: "彼は資力を超えた生活をしている。" },
        { sentence: "I have to make it a ___ to cook more at home.", answer: "habit", base: "habit", hint: "h____", ja: "習慣、癖", sentenceJa: "もっと家で料理をする習慣をつけなければなりません。" },
        { sentence: "We were stuck in a traffic ___ for two hours.", answer: "jam", base: "jam", hint: "j__", ja: "ジャム、渋滞、詰まる", sentenceJa: "私たちは2時間渋滞にはまってしまいました。" },
        { sentence: "Do you have any ___ for learning English faster?", answer: "tips", base: "tip", hint: "t__", ja: "助言、コツ、チップ、一角", sentenceJa: "英語を早く習得するためのヒントはありますか?" },
        { sentence: "Can you guys make ___ so my friend can sit down?", answer: "room", base: "room", hint: "r___", ja: "部屋、スペース", sentenceJa: "私の友達が座れるように場所を作ってもらえませんか？" },
        { sentence: "She has a really positive ___ towards life.", answer: "attitude", base: "attitude", hint: "a_______", ja: "態度、考え方、姿勢", sentenceJa: "彼女は人生に対して本当に前向きな姿勢を持っています。" },
        { sentence: "The ___ arrived this morning.", answer: "package", base: "package", hint: "p______", ja: "荷物、パッケージ、セット、まとめ", sentenceJa: "今朝荷物が届きました。" },
      ],
    },
    {
      name: "Day 23",
      items: [
        { sentence: "Excuse me, is this room ___ to book?", answer: "available", base: "available", hint: "a________", ja: "利用可能な、空いている、対応可能", sentenceJa: "すみません、この部屋は予約できますか?" },
        { sentence: "___ one is fine.", answer: "either", base: "either", hint: "e_____", ja: "どちらか一方、どちらでもOK、どちらでもない", sentenceJa: "どちらでも大丈夫です。" },
        { sentence: "In ___, I don't eat sweets.", answer: "general", base: "general", hint: "g______", ja: "一般的な、基本的に(in general)、大まかな、全体的な", sentenceJa: "基本的に私は甘いものは食べません。" },
        { sentence: "I just ran into my ___ boss today.", answer: "former", base: "former", hint: "f_____", ja: "もとの、前者", sentenceJa: "今日、元上司に偶然会いました。" },
        { sentence: "It's very ___ to live across from a grocery store.", answer: "convenient", base: "convenient", hint: "c_________", ja: "便利な、使い勝手がいい、やりやすい、無理がない", sentenceJa: "スーパーの向かいに住むのはとても便利です。" },
        { sentence: "Oh my gosh, I’m ___.", answer: "jealous", base: "jealous", hint: "j______", ja: "嫉妬している、羨ましい", sentenceJa: "あらまあ、うらやましい。" },
        { sentence: "Who's ___ for this mess!", answer: "responsible", base: "responsible", hint: "r__________", ja: "責任がある", sentenceJa: "この混乱の責任は誰だ！" },
        { sentence: "He's really ___.", answer: "reliable", base: "reliable", hint: "r_______", ja: "信頼できる、頼りになる", sentenceJa: "彼は本当に信頼できるよ。" },
        { sentence: "Try to stay ___, even when things are tough.", answer: "positive", base: "positive", hint: "p_______", ja: "前向きな、陽性、確信している", sentenceJa: "たとえ困難なことがあっても、ポジティブでいることを心がけてください。" },
        { sentence: "He is ___ in volunteer work.", answer: "engaged", base: "engaged", hint: "e______", ja: "一生懸命やっている、熱心に取り組んでいる、集中して関わっている、本気で取り組んでいる、婚約している", sentenceJa: "彼はボランティア活動に従事しています。" },
        { sentence: "Your hair is so ___!", answer: "messy", base: "messy", hint: "m____", ja: "片付いていない、ぐちゃぐちゃだ、ややこしい", sentenceJa: "髪がすごく乱れているよ！" },
        { sentence: "The court found him ___ of murder.", answer: "guilty", base: "guilty", hint: "g_____", ja: "有罪の、悪いことをした(と思う)当事者、バツの悪い", sentenceJa: "裁判所は彼に殺人罪で有罪判決を下した。" },
        { sentence: "I'm ___.", answer: "curious", base: "curious", hint: "c______", ja: "好奇心旺盛な、知りたい、教えて、欲しい、気になる、少し変わった、妙な", sentenceJa: "興味があります。" },
        { sentence: "This puzzle is ___.", answer: "challenging", base: "challenging", hint: "c__________", ja: "挑戦的な、難しい、手強い", sentenceJa: "このパズルは難しいです。" },
        { sentence: "Regular exercise is ___ in the long run.", answer: "beneficial", base: "beneficial", hint: "b_________", ja: "プラスになる、ためになる、得になる", sentenceJa: "定期的な運動は長期的には有益です。" },
        { sentence: "Make sure the website has the ___ information before you copy it.", answer: "latest", base: "latest", hint: "l_____", ja: "一番新しい、最新の", sentenceJa: "コピーする前に、Webサイトに最新の情報があるか確認して。" },
        { sentence: "Everyone was ___ in class today.", answer: "present", base: "present", hint: "p______", ja: "現状の、今の、出席している、存在している", sentenceJa: "今日は全員が授業に出席していました。" },
        { sentence: "Each ___ student received feedback.", answer: "individual", base: "individual", hint: "i_________", ja: "個々の", sentenceJa: "生徒一人ひとりがフィードバックを受けました。" },
        { sentence: "The store is under ___ closure for renovations.", answer: "temporary", base: "temporary", hint: "t________", ja: "長く続かない、とりあえず今だけ", sentenceJa: "その店は改装のため一時休業中です。" },
        { sentence: "The line is ___ right now.", answer: "occupied", base: "occupied", hint: "o_______", ja: "使用中、空きがない", sentenceJa: "ただいま話し中です。" },
      ],
    },
    {
      name: "Day 24",
      items: [
        { sentence: "I can ___ make it.", answer: "probably", base: "probably", hint: "p_______", ja: "おそらく、多分", sentenceJa: "たぶんできるよ。" },
        { sentence: "___, I've already seen that movie.", answer: "actually", base: "actually", hint: "a_______", ja: "実際は、実は、まさかの、やっぱりさ", sentenceJa: "実は私はもうその映画を見ました。" },
        { sentence: "I ___ like Thai curry.", answer: "especially", base: "especially", hint: "e_________", ja: "特に", sentenceJa: "特にタイカレーが好きです。" },
        { sentence: "___, we're supposed to write down everything, but no one does.", answer: "technically", base: "technically", hint: "t__________", ja: "厳密に、規則上は、図面上は、建前上は", sentenceJa: "厳密に言えば、すべてを書き留める必要がありますが、誰もそれをしません。" },
        { sentence: "We have ___ 5 minutes left.", answer: "literally", base: "literally", hint: "l________", ja: "文字通りに、マジで、本当に", sentenceJa: "残り時間は本当に5分しかありません。" },
        { sentence: "My mood improves ___ after coffee.", answer: "dramatically", base: "dramatically", hint: "d___________", ja: "劇的に、ガラッと、一気に、段違いに、大幅に、大げさに", sentenceJa: "コーヒーを飲むと気分が劇的に良くなります。" },
        { sentence: "I'll ___ come back here.", answer: "definitely", base: "definitely", hint: "d_________", ja: "明確に、確実に、絶対、必ず、もちろん", sentenceJa: "必ずここに戻ってきます。" },
        { sentence: "That's ___ different.", answer: "totally", base: "totally", hint: "t______", ja: "全く、すっかり、完全に", sentenceJa: "それは全く違います。" },
        { sentence: "They're ___ the same.", answer: "basically", base: "basically", hint: "b________", ja: "基本的に、要するに、ざっくり言うと、ぶっちゃけ、正直なところ、まあそんな感じ", sentenceJa: "基本的には同じです。" },
        { sentence: "He was ___ upset.", answer: "obviously", base: "obviously", hint: "o________", ja: "明らかに、見るからに、どう考えても", sentenceJa: "彼は明らかに動揺していました。" },
        { sentence: "Are you ___ working?", answer: "still", base: "still", hint: "s____", ja: "まだ、まだ〜していない、今でも、それでも、じっとして、動かないで", sentenceJa: "まだ働いていますか？" },
        { sentence: "I'm ___ excited about the trip.", answer: "low-key", base: "low-key", hint: "l______", ja: "控えめな、ちょっと、地味に", sentenceJa: "旅行がちょっと楽しみです。" },
        { sentence: "Please stand two meters ___.", answer: "apart", base: "apart", hint: "a____", ja: "離れて、以外、除いて、以外に加えて、(時間的に)離れて", sentenceJa: "2メートル間隔を空けて立って。" },
        { sentence: "She's ___ checking her phone.", answer: "constantly", base: "constantly", hint: "c_________", ja: "常に、しょっちゅう、いつも", sentenceJa: "彼女は常に携帯電話をチェックしています。" },
        { sentence: "Are you ___ going to quit?", answer: "seriously", base: "seriously", hint: "s________", ja: "真剣に、本気で、マジで", sentenceJa: "本気で辞める気あるの？" },
        { sentence: "I ___ don't understand.", answer: "simply", base: "simply", hint: "s_____", ja: "単に", sentenceJa: "単純に理解できません。" },
        { sentence: "I'd ___ recommend this one.", answer: "personally", base: "personally", hint: "p_________", ja: "個人的には、私だったら", sentenceJa: "個人的にはこれをお勧めします。" },
        { sentence: "She's ___ good at drawing.", answer: "naturally", base: "naturally", hint: "n________", ja: "自然に、もともと、無理なく、スッと", sentenceJa: "彼女はもともと絵を描くのが上手です。" },
        { sentence: "I've ___ eaten.", answer: "already", base: "already", hint: "a______", ja: "すでに、もう", sentenceJa: "もう食べてしまいました。" },
        { sentence: "I visit my parents quite ___.", answer: "frequently", base: "frequently", hint: "f_________", ja: "頻繁に", sentenceJa: "私は両親を頻繁に訪ねます。" },
      ],
    },
    {
      name: "Day 25",
      items: [
        { sentence: "My car ___ on the side of the highway.", answer: "broke down", base: "break down", hint: "b_________", ja: "壊れる、細分化する、噛み砕いて説明する", sentenceJa: "私の車は高速道路の脇で故障しました。" },
        { sentence: "How did you ___ the idea for your book?", answer: "come up with", base: "come up with", hint: "c___________", ja: "～を思いつく", sentenceJa: "あなたの本のアイデアはどのように思いついたのですか？" },
        { sentence: "Please don’t be mad. I didn’t do it ___.", answer: "on purpose", base: "on purpose", hint: "o_________", ja: "わざと", sentenceJa: "怒らないで。わざとやったわけじゃない。" },
        { sentence: "I was gonna buy something to drink, but it was ___.", answer: "out of order", base: "out of order", hint: "o___________", ja: "故障中", sentenceJa: "何か飲み物を買おうとしたのですが、故障中でした。" },
        { sentence: "I’m ___ chicken.", answer: "sick of", base: "be sick of", hint: "b_________", ja: "～にうんざりしている", sentenceJa: "チキンにはうんざりです。" },
        { sentence: "We finally met ___ after a year of dating online.", answer: "in person", base: "in person", hint: "i________", ja: "直接会って", sentenceJa: "オンラインで1年間付き合ったあと、私たちはついに直接会いました。" },
        { sentence: "I’d like to gossip, but that’s ___.", answer: "none of my business", base: "none of one's business", hint: "n_____________________", ja: "～(人)には関係ない", sentenceJa: "うわさ話はしたいけれど、それは私には関係ないことです。" },
        { sentence: "You have to give kids freedom ___.", answer: "to some extent", base: "to some extent", hint: "t_____________", ja: "ある程度は", sentenceJa: "子どもにはある程度自由を与えなければなりません。" },
        { sentence: "___ wine, I prefer red.", answer: "when it comes to", base: "when it comes to", hint: "w_______________", ja: "～ということになると、～に関しては", sentenceJa: "ワインのことになると、私は赤のほうが好きです。" },
        { sentence: "Are we talking ___ dollars or yen?", answer: "in terms of", base: "in terms of", hint: "i__________", ja: "～の観点で", sentenceJa: "ドルと円のどちらの単位で話していますか？" },
      ],
    },
    {
      name: "Day 26",
      items: [
        { sentence: "I don't ___ cooking tonight.", answer: "feel like", base: "feel like", hint: "f________", ja: "〜したい気分だ", sentenceJa: "今夜は料理をする気分じゃない。" },
        { sentence: "This tie doesn't ___ your shirt.", answer: "go with", base: "go with", hint: "g______", ja: "合う、選ぶ", sentenceJa: "このネクタイはあなたのシャツに合わない。" },
        { sentence: "I sent the email to the wrong person ___.", answer: "by mistake", base: "by mistake", hint: "b_________", ja: "間違って", sentenceJa: "私は間違って別の人にメールを送ってしまった。" },
        { sentence: "We ___ milk this morning.", answer: "ran out of", base: "run out of", hint: "r_________", ja: "〜を使い果たす", sentenceJa: "今朝、牛乳を切らしてしまった。" },
        { sentence: "We often ___ that clean water is always available.", answer: "take for granted", base: "take for granted", hint: "t_______________", ja: "当然のことと思う", sentenceJa: "私たちはきれいな水がいつでも手に入ることを当然だと思いがちだ。" },
        { sentence: "He ___ talk too fast when he's nervous.", answer: "tends to", base: "tend to", hint: "t______", ja: "〜しがちである", sentenceJa: "彼は緊張すると早口になりがちだ。" },
        { sentence: "Let's ___ each other over coffee.", answer: "catch up with", base: "catch up with", hint: "c____________", ja: "追いつく、近況を語り合う", sentenceJa: "コーヒーでも飲みながら近況を話そう。" },
        { sentence: "I don't know ___ if she's coming.", answer: "for sure", base: "for sure", hint: "f_______", ja: "確かに、間違いなく", sentenceJa: "彼女が来るかどうか確かなことは分からない。" },
        { sentence: "She ___ everyone in the office.", answer: "gets along with", base: "get along with", hint: "g_____________", ja: "仲良くやっていく", sentenceJa: "彼女はオフィスの誰とでもうまくやっている。" },
        { sentence: "The plan sounds simple, but ___ it's quite complex.", answer: "in reality", base: "in reality", hint: "i_________", ja: "実際には", sentenceJa: "その計画は単純に聞こえるが、実際にはかなり複雑だ。" },
        { sentence: "___ the rain, they finished the game.", answer: "in spite of", base: "in spite of", hint: "i__________", ja: "〜にもかかわらず", sentenceJa: "雨にもかかわらず、彼らは試合を終えた。" },
        { sentence: "They tried ___ to fix the old engine.", answer: "in vain", base: "in vain", hint: "i______", ja: "無駄に", sentenceJa: "彼らはその古いエンジンを直そうとしたが無駄だった。" },
        { sentence: "She ___ a difficult time last year.", answer: "went through", base: "go through", hint: "g_________", ja: "経験する、目を通す", sentenceJa: "彼女は去年、辛い時期を経験した。" },
        { sentence: "Are you ___ this software?", answer: "familiar with", base: "familiar with", hint: "f____________", ja: "〜に詳しい、慣れている", sentenceJa: "このソフトウェアに詳しいですか。" },
        { sentence: "He's always ___ help his classmates.", answer: "willing to", base: "willing to", hint: "w_________", ja: "〜する意思がある", sentenceJa: "彼はいつでもクラスメートを進んで手伝う。" },
        { sentence: "You can leave early, ___ you finish your work.", answer: "provided that", base: "provided that", hint: "p____________", ja: "〜という条件で", sentenceJa: "仕事を終わらせるという条件で、早く帰ってもいいですよ。" },
        { sentence: "He likes to ___ his new car.", answer: "show off", base: "show off", hint: "s_______", ja: "見せびらかす", sentenceJa: "彼は新しい車を見せびらかすのが好きだ。" },
        { sentence: "___, the truth always comes out.", answer: "sooner or later", base: "sooner or later", hint: "s______________", ja: "遅かれ早かれ", sentenceJa: "遅かれ早かれ、真実は必ず明らかになる。" },
        { sentence: "It's hard to ___ all these changes.", answer: "keep up with", base: "keep up with", hint: "k___________", ja: "遅れずについていく", sentenceJa: "これらすべての変化についていくのは難しい。" },
        { sentence: "I'm ___ the gym now.", answer: "off to", base: "off to", hint: "o_____", ja: "〜に向かって、出かけて", sentenceJa: "私は今からジムに向かいます。" },
      ],
    },
    {
      name: "Day 27",
      items: [
        { sentence: "Please ___ your assignment by Friday.", answer: "turn in", base: "turn in", hint: "t______", ja: "提出する", sentenceJa: "金曜日までに課題を提出してください。" },
        { sentence: "She ___ a lot of effort on this project.", answer: "put in", base: "put in", hint: "p_____", ja: "（時間や労力を）注ぐ", sentenceJa: "彼女はこのプロジェクトにたくさんの労力を注いだ。" },
        { sentence: "There was too much information to ___ at once.", answer: "take in", base: "take in", hint: "t______", ja: "理解する、吸収する", sentenceJa: "一度に理解するには情報が多すぎた。" },
        { sentence: "He kept ___ while I was talking.", answer: "cutting in", base: "cut in", hint: "c_____", ja: "割り込む", sentenceJa: "私が話している間、彼はずっと割り込んできた。" },
        { sentence: "Someone tried to ___ through the back door.", answer: "break in", base: "break in", hint: "b_______", ja: "侵入する", sentenceJa: "誰かが裏口から侵入しようとした。" },
        { sentence: "She ___ her coat before leaving.", answer: "put on", base: "put on", hint: "p_____", ja: "身につける", sentenceJa: "彼女は出かける前にコートを着た。" },
        { sentence: "Yesterday, we ___ the bus just in time.", answer: "got on", base: "get on", hint: "g_____", ja: "乗る、うまくやっていく", sentenceJa: "昨日、私たちはちょうど間に合ってバスに乗った。" },
        { sentence: "You can always ___ your family.", answer: "rely on", base: "rely on", hint: "r______", ja: "頼る", sentenceJa: "家族にはいつでも頼れる。" },
        { sentence: "I'm ___ my presentation for tomorrow.", answer: "working on", base: "work on", hint: "w______", ja: "取り組む", sentenceJa: "私は明日のプレゼンテーションに取り組んでいる。" },
        { sentence: "It's time to ___ from that mistake.", answer: "move on", base: "move on", hint: "m______", ja: "気持ちを切り替える、次に進む", sentenceJa: "その失敗から気持ちを切り替える時だ。" },
        { sentence: "Let's ___ the numbers more closely.", answer: "look at", base: "look at", hint: "l______", ja: "見る、検討する", sentenceJa: "その数字をもっと詳しく見てみましょう。" },
        { sentence: "Last night, we finally ___ a decision after hours of discussion.", answer: "arrived at", base: "arrive at", hint: "a________", ja: "到着する、（結論に）達する", sentenceJa: "昨夜、何時間も議論した末、私たちはついに結論に達した。" },
        { sentence: "You should ___ your doctor's advice.", answer: "listen to", base: "listen to", hint: "l________", ja: "耳を傾ける", sentenceJa: "医者の助言に耳を傾けるべきだ。" },
        { sentence: "I need to ___ my manager about this.", answer: "talk to", base: "talk to", hint: "t______", ja: "話しかける", sentenceJa: "この件について上司と話す必要がある。" },
        { sentence: "She ___ several local charities.", answer: "gives to", base: "give to", hint: "g______", ja: "（慈善などに）寄付する、与える", sentenceJa: "彼女はいくつかの地元の慈善団体に寄付をしている。" },
        { sentence: "It took weeks to ___ the flu.", answer: "recover from", base: "recover from", hint: "r___________", ja: "回復する", sentenceJa: "インフルエンザから回復するのに数週間かかった。" },
        { sentence: "Last spring, they ___ the small mountain town.", answer: "fell in love with", base: "fall in love with", hint: "f________________", ja: "恋に落ちる、大好きになる", sentenceJa: "去年の春、彼らはその小さな山の町に魅了された。" },
        { sentence: "We need to ___ this issue right away.", answer: "deal with", base: "deal with", hint: "d________", ja: "対処する", sentenceJa: "私たちはこの問題にすぐに対処する必要がある。" },
        { sentence: "I'm ___ my keys.", answer: "looking for", base: "look for", hint: "l_______", ja: "探す", sentenceJa: "私は鍵を探している。" },
        { sentence: "Yesterday, we ___ the bus in the rain.", answer: "waited for", base: "wait for", hint: "w_______", ja: "待つ", sentenceJa: "昨日、私たちは雨の中バスを待った。" },
      ],
    },
    {
      name: "Day 29",
      items: [
        { sentence: "Don't be afraid to ___ help.", answer: "ask for", base: "ask for", hint: "a______", ja: "求める、頼む", sentenceJa: "遠慮せずに助けを求めてください。" },
        { sentence: "I'll ___ dinner tonight.", answer: "pay for", base: "pay for", hint: "p______", ja: "代金を払う", sentenceJa: "今夜の夕食は私が払います。" },
        { sentence: "Feel free to ___ anytime.", answer: "drop by", base: "drop by", hint: "d______", ja: "ちょっと立ち寄る", sentenceJa: "いつでも気軽に立ち寄ってください。" },
        { sentence: "I'll ___ you no matter what happens.", answer: "stand by", base: "stand by", hint: "s_______", ja: "支持する、待機する", sentenceJa: "何があっても私はあなたを支えます。" },
        { sentence: "Yesterday, we ___ the old church on our walk.", answer: "passed by", base: "pass by", hint: "p______", ja: "通り過ぎる", sentenceJa: "昨日、散歩の途中、私たちはその古い教会を通り過ぎた。" },
        { sentence: "Yesterday, he ___ his phone to check the time.", answer: "took out", base: "take out", hint: "t_______", ja: "取り出す、連れ出す", sentenceJa: "昨日、彼は時間を確認するために携帯を取り出した。" },
        { sentence: "Last month, the truth finally ___ after the investigation.", answer: "came out", base: "come out", hint: "c_______", ja: "明らかになる、発売される", sentenceJa: "先月、調査の後、ついに真実が明らかになった。" },
        { sentence: "The party ___ better than we expected.", answer: "turned out", base: "turn out", hint: "t_______", ja: "結局〜になる、判明する", sentenceJa: "パーティーは予想していたよりも良い結果になった。" },
        { sentence: "You should ___ this new restaurant.", answer: "check out", base: "check out", hint: "c________", ja: "確認する、チェックアウトする", sentenceJa: "この新しいレストランを確認してみるといいよ。" },
        { sentence: "We're ___ for dinner this weekend.", answer: "going out", base: "go out", hint: "g_____", ja: "出かける", sentenceJa: "私たちは今週末、夕食に出かける予定だ。" },
        { sentence: "I need to ___ what time the store closes.", answer: "find out", base: "find out", hint: "f_______", ja: "知る、突き止める", sentenceJa: "その店が何時に閉まるか調べる必要がある。" },
        { sentence: "I ___ early this morning.", answer: "woke up", base: "wake up", hint: "w______", ja: "目が覚める", sentenceJa: "私は今朝早く目が覚めた。" },
        { sentence: "Can you ___ some milk on your way home?", answer: "pick up", base: "pick up", hint: "p______", ja: "拾う、迎えに行く、覚える", sentenceJa: "帰りに牛乳を買ってきてくれますか。" },
        { sentence: "Years ago, she ___ in a small town.", answer: "grew up", base: "grow up", hint: "g______", ja: "成長する、育つ", sentenceJa: "何年も前、彼女は小さな町で育った。" },
        { sentence: "He didn't ___ for the meeting.", answer: "show up", base: "show up", hint: "s______", ja: "現れる", sentenceJa: "彼は会議に現れなかった。" },
        { sentence: "Can you ___ the leftovers?", answer: "heat up", base: "heat up", hint: "h______", ja: "温める", sentenceJa: "残り物を温めてもらえますか。" },
        { sentence: "Last year, they ___ after two years together.", answer: "broke up", base: "break up", hint: "b_______", ja: "別れる、分裂する", sentenceJa: "去年、彼らは2年間付き合った後、別れた。" },
        { sentence: "I need to ___ on my reading.", answer: "catch up", base: "catch up", hint: "c_______", ja: "追いつく、近況を話す", sentenceJa: "読書の遅れを取り戻す必要がある。" },
        { sentence: "Don't ___ on your dreams.", answer: "give up", base: "give up", hint: "g______", ja: "あきらめる", sentenceJa: "夢をあきらめないで。" },
      ],
    },
    {
      name: "Day 30",
      items: [
        { sentence: "Last night, he ___ not to notice the mistake.", answer: "pretended", base: "pretend", hint: "p______", ja: "ふりをする", sentenceJa: "昨夜、彼はその間違いに気づかないふりをした。" },
        { sentence: "Please ___ the staples before recycling the paper.", answer: "remove", base: "remove", hint: "r_____", ja: "取り除く", sentenceJa: "紙をリサイクルする前にホチキスの針を取り除いてください。" },
        { sentence: "He couldn't ___ the constant noise from the construction site.", answer: "stand", base: "stand", hint: "s____", ja: "立つ、耐える", sentenceJa: "彼は工事現場からの絶え間ない騒音に耐えられなかった。" },
        { sentence: "Currently, this issue ___ everyone in the department.", answer: "concerns", base: "concern", hint: "c______", ja: "心配させる、関係する", sentenceJa: "現在、この問題は部署の全員に関係している。" },
        { sentence: "Last year, the committee finally ___ her contribution to the project.", answer: "recognized", base: "recognize", hint: "r________", ja: "認識する、見分ける、認める", sentenceJa: "昨年、委員会は最終的に彼女のプロジェクトへの貢献を認めた。" },
        { sentence: "Yesterday, workers ___ a trench for the new pipeline.", answer: "dug", base: "dig", hint: "d__", ja: "掘る", sentenceJa: "昨日、作業員たちは新しいパイプラインのために溝を掘った。" },
        { sentence: "Yesterday, rumors about the merger ___ quickly through the office.", answer: "spread", base: "spread", hint: "s_____", ja: "広げる、広がる", sentenceJa: "昨日、合併についての噂がオフィス中に素早く広まった。" },
        { sentence: "Please don't ___ the meeting in progress.", answer: "disturb", base: "disturb", hint: "d______", ja: "邪魔する", sentenceJa: "進行中の会議の邪魔をしないでください。" },
        { sentence: "Last week, the new manager ___ the crisis calmly.", answer: "handled", base: "handle", hint: "h_____", ja: "扱う、対処する、手を触れる", sentenceJa: "先週、新しいマネージャーはその危機に冷静に対処した。" },
        { sentence: "Yesterday, they ___ an entire day arguing over minor details.", answer: "wasted", base: "waste", hint: "w____", ja: "無駄にする", sentenceJa: "昨日、彼らは些細な事について言い争って丸一日を無駄にした。" },
        { sentence: "Could you ___ transportation for the visiting clients?", answer: "arrange", base: "arrange", hint: "a______", ja: "手配する、整える", sentenceJa: "訪問客のための交通手段を手配していただけますか？" },
        { sentence: "Investors increasingly ___ sustainable companies to fund.", answer: "seek", base: "seek", hint: "s___", ja: "探し求める", sentenceJa: "投資家はますます持続可能な企業への投資を求めている。" },
        { sentence: "This factory ___ parts to three major manufacturers.", answer: "supplies", base: "supply", hint: "s_____", ja: "供給する", sentenceJa: "この工場は3つの大手メーカーに部品を供給している。" },
        { sentence: "The inheritance was ___ equally among the siblings.", answer: "divided", base: "divide", hint: "d_____", ja: "分ける、割る", sentenceJa: "その遺産は兄弟姉妹の間で均等に分けられた。" },
        { sentence: "Yesterday, he ___ a note on the fridge before heading to work.", answer: "left", base: "leave", hint: "l____", ja: "去る、残す、置き忘れる", sentenceJa: "昨日、彼は仕事に行く前に冷蔵庫にメモを残した。" },
        { sentence: "The new employees always ___ the safety checklist.", answer: "follow", base: "follow", hint: "f_____", ja: "ついていく、従う", sentenceJa: "新入社員はいつも安全チェックリストに従う。" },
        { sentence: "The curtains were ___ to block the afternoon sun.", answer: "drawn", base: "draw", hint: "d___", ja: "描く、引く", sentenceJa: "午後の日差しを遮るためにカーテンが引かれた。" },
        { sentence: "The seminar will ___ advanced negotiation techniques.", answer: "cover", base: "cover", hint: "c____", ja: "覆う、（話題を）扱う", sentenceJa: "そのセミナーは高度な交渉術を扱う予定だ。" },
        { sentence: "Last year, early feedback from users ___ the final design.", answer: "shaped", base: "shape", hint: "s____", ja: "形作る", sentenceJa: "昨年、ユーザーからの初期のフィードバックが最終デザインを形作った。" },
        { sentence: "Ticket prices will ___ unchanged next season.", answer: "remain", base: "remain", hint: "r_____", ja: "とどまる、～のままである、残る", sentenceJa: "チケット価格は来シーズンも変わらない予定だ。" },
      ],
    },
  ],
};
